In [79]:
import pandas as pd
import glob
import os
import re

# Education

In [80]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [81]:
# Path to your Education folder (go one level up first)
folder_path = os.path.join("..", "raw", "Education")

# Find all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

dfs = []
for file in csv_files:
    # Extract year from filename (e.g., Education_2019.csv → 2019)
    year = os.path.splitext(os.path.basename(file))[0].split("_")[-1]
    
    df = pd.read_csv(file)
    df["year"] = year   # Add year column
    dfs.append(df)

# Combine all with year included
edu_df = pd.concat(dfs, ignore_index=True)


print(f"Found {len(csv_files)} CSV files:")
for file in csv_files:
    print(f" - {os.path.basename(file)}")


print(edu_df.head())

C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,6,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,66,70,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,160,161,164,165,168,169,172,173,176,177,180,181,182,186,190,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,222,226,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,258,262,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,294,298,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,330,331,334,335,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,366,367,370,371,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,402,403,406,407,410,411,414,415,418,419,422,423,426,427,430,431,434,435,438,439,442,443,446,447,450,451,454,455,458,459,462,463,466,467,470,471,474,475,478,479,482,483,486,487,490,491,494,495,498,499,502,503,506,507,510,511,514,515,518,519,522,523,526,527,530,531,534,535,538,539,542,543,546,547,550,551,554,555,558,559,562,563,566,567,570,571,574,575,578,579,582,583,586,587,590,591,594,595,598,599,602,603,606,607,610,611,614,618,622,626,627,628,629,630,631,634,635,638,639,640,641,642,643,646,647,652,653,656,657,660,661,664,665,668,669,672,673,676,677,680,681,684,685,688,689,692,693,696,697) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,6,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,66,70,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,160,161,164,165,168,169,172,173,176,177,180,181,182,186,190,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,222,226,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,258,262,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,294,298,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,330,331,334,335,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,366,367,370,371,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,402,403,406,407,410,411,414,415,418,419,422,423,426,427,430,431,434,435,438,439,442,443,446,447,450,451,454,455,458,459,462,463,466,467,470,471,474,475,478,479,482,483,486,487,490,491,494,495,498,499,502,503,506,507,510,511,514,515,518,519,522,523,526,527,530,531,534,535,538,539,542,543,546,547,550,551,554,555,558,559,562,563,566,567,570,571,574,575,578,579,582,583,586,587,590,591,594,595,598,599,602,603,606,607,610,611,614,618,622,626,627,628,629,630,631,634,635,638,639,640,641,642,643,646,647,652,653,656,657,660,661,664,665,668,669,672,673,676,677,680,681,684,685,688,689,692,693,696,697,698,699,702,703,706,707,722,723,726,727,734,735,742,743,746,747,754,755) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,32,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,108,109,118,119,122,123,124,125,126,127,132,133,134,135,136,137,138,139,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,162,163,164,165,168,169,170,171,174,175,176,177,180,181,182,183,186,187,188,189,192,193,194,195,234,235,236,237,238,239,240,241,242,243,244,245,258,260,261,262,263,264,265,266,267,268,270,271,272,273,274,275,276,277,278,279,280,281,282,283,288,290,291,292,293,294,296,297,298,299,300,302,303,304,305,306,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,362,363,364,365,374,375,378,379,388,389,390,391,392,393,394,395,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,418,419,420,421,424,425,426,427,430,431,432,433,436,437,438,439,442,443,444,445,448,449,450,451,494,495,496,497,498,499,500,501,514,516,517,518,519,520,521,522,523,524,526,527,528,529,530,531,532,533,534,535,536,537,538,539,544,546,547,548,549,550,552,553,554,555,556,558,559,560,561,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,618,619,620,621,630,631,634,635,636,637,644,645,646,647,648,649,650,651,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,674,675,676,677,680,681,682,683,686,687,688,689,692,693,694,695,698,699,700,701,704,705,706,707,750,751,752,753,754,755,756,757) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,108,109,118,119,122,123,124,125,132,136,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,182,186,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,264,265,268,269,270,271,274,275,278,279,282,286,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,312,316,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,342,346,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,372,376,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,402,403,406,407,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,432,433,436,437,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,462,463,466,467,472,473,476,477,482,483,486,487,492,493,496,497,502,503,506,507,512,513,516,517,522,523,526,527,532,533,536,537,542,543,546,547,552,553,556,557,562,563,566,567,572,573,576,577,582,583,586,587,592,593,596,597,602,603,606,607,612,613,616,617,622,623,626,627,632,633,636,637,642,646,650,651,652,653,656,657,660,661,662,663,666,667,670,671,674,675,678,679,680,681,684,685,688,689,690,691,694,695,698,699,700,701,704,705,708,709,712,713,716,717,732,733) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,108,109,118,119,122,123,124,125,132,133,134,135,136,137,138,139,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,162,163,164,165,168,169,170,171,174,175,176,177,180,181,182,183,186,187,188,189,192,193,194,195,234,235,236,237,238,239,240,241,242,243,244,245,258,260,261,262,263,264,265,266,267,268,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,290,291,292,293,294,296,297,298,299,300,302,303,304,305,306,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,362,363,364,365,374,375,378,379,380,381,388,389,390,391,392,393,394,395,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,418,419,420,421,424,425,426,427,430,431,432,433,436,437,438,439,442,443,444,445,448,449,450,451,494,495,496,497,498,499,500,501,514,516,517,518,519,520,521,522,523,524,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,546,547,548,549,550,552,553,554,555,556,558,559,560,561,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,618,619,620,621,630,631,644,645,646,647,648,649,650,651,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,674,675,676,677,680,681,682,683,686,687,688,689,692,693,694,695,698,699,700,701,704,705,706,707,750,751,752,753,754,755,756,757) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,108,109,118,119,122,123,124,125,132,133,134,135,136,137,138,139,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,162,163,164,165,168,169,170,171,174,175,176,177,180,181,182,183,186,187,188,189,192,193,194,195,228,229,230,231,234,235,236,237,238,239,240,241,242,243,244,245,258,260,261,262,263,264,265,266,267,268,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,290,291,292,293,294,296,297,298,299,300,302,303,304,305,306,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,362,363,364,365,374,375,378,379,380,381,388,389,390,391,392,393,394,395,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,418,419,420,421,424,425,426,427,430,431,432,433,436,437,438,439,442,443,444,445,448,449,450,451,494,495,496,497,498,499,500,501,514,516,517,518,519,520,521,522,523,524,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,546,547,548,549,550,552,553,554,555,556,558,559,560,561,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,618,619,620,621,630,631,644,645,646,647,648,649,650,651,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,674,675,676,677,680,681,682,683,686,687,688,689,692,693,694,695,698,699,700,701,704,705,706,707,750,751,752,753,754,755,756,757) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,108,109,118,119,122,123,124,125,132,133,134,135,136,137,138,139,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,162,163,164,165,168,169,170,171,174,175,176,177,180,181,182,183,186,187,188,189,192,193,194,195,228,229,230,231,238,239,240,241,242,243,244,245,258,260,261,262,263,264,265,266,267,268,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,290,291,292,293,294,296,297,298,299,300,302,303,304,305,306,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,362,363,364,365,374,375,388,389,390,391,392,393,394,395,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,418,419,420,421,424,425,426,427,430,431,432,433,436,437,438,439,442,443,444,445,448,449,450,451,484,485,486,487,494,495,496,497,498,499,500,501,514,516,517,518,519,520,521,522,523,524,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,546,547,548,549,550,552,553,554,555,556,558,559,560,561,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,618,619,620,621,630,631,644,645,646,647,648,649,650,651,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,674,675,676,677,680,681,682,683,686,687,688,689,692,693,694,695,698,699,700,701,704,705,706,707,750,751,752,753,754,755,756,757) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,108,109,118,119,122,123,124,125,132,133,134,135,136,137,138,139,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,162,163,164,165,168,169,170,171,174,175,176,177,180,181,182,183,186,187,188,189,192,193,194,195,228,229,230,231,238,239,240,241,242,243,244,245,258,260,261,262,263,264,265,266,267,268,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,290,291,292,293,294,296,297,298,299,300,302,303,304,305,306,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,362,363,364,365,374,375,378,379,380,381,388,389,390,391,392,393,394,395,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,418,419,420,421,424,425,426,427,430,431,432,433,436,437,438,439,442,443,444,445,448,449,450,451,484,485,486,487,494,495,496,497,498,499,500,501,514,516,517,518,519,520,521,522,523,524,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,546,547,548,549,550,552,553,554,555,556,558,559,560,561,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,618,619,620,621,630,631,636,637,644,645,646,647,648,649,650,651,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,674,675,676,677,680,681,682,683,686,687,688,689,692,693,694,695,698,699,700,701,704,705,706,707,750,751,752,753,754,755,756,757) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\2119792862.py:12: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,108,109,118,119,122,123,124,125,132,133,134,135,136,137,138,139,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,162,163,164,165,168,169,170,171,174,175,176,177,180,181,182,183,186,187,188,189,192,193,194,195,238,239,240,241,242,243,244,245,258,260,261,262,263,264,265,266,267,268,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,290,291,292,293,294,296,297,298,299,300,302,303,304,305,306,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,362,363,364,365,374,375,378,379,388,389,390,391,392,393,394,395,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,418,419,420,421,424,425,426,427,430,431,432,433,436,437,438,439,442,443,444,445,448,449,450,451,494,495,496,497,498,499,500,501,514,516,517,518,519,520,521,522,523,524,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,546,547,548,549,550,552,553,554,555,556,558,559,560,561,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,618,619,620,621,630,631,636,637,644,645,646,647,648,649,650,651,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,674,675,676,677,680,681,682,683,686,687,688,689,692,693,694,695,698,699,700,701,704,705,706,707,750,751,752,753,754,755,756,757) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Found 115 CSV files:
 - alabama_edu_15.csv
 - alabama_edu_16.csv
 - alabama_edu_17.csv
 - alabama_edu_18.csv
 - alabama_edu_19.csv
 - alabama_edu_20.csv
 - alabama_edu_21.csv
 - alabama_edu_22.csv
 - alabama_edu_23.csv
 - georgia_edu_15.csv
 - georgia_edu_16.csv
 - georgia_edu_17.csv
 - georgia_edu_18.csv
 - georgia_edu_19.csv
 - georgia_edu_20.csv
 - georgia_edu_21.csv
 - georgia_edu_22.csv
 - georgia_edu_23.csv
 - kentucky_edu_15.csv
 - kentucky_edu_16.csv
 - kentucky_edu_17.csv
 - kentucky_edu_18.csv
 - kentucky_edu_19.csv
 - kentucky_edu_20.csv
 - kentucky_edu_21.csv
 - kentucky_edu_22.csv
 - kentucky_edu_23.csv
 - maryland_edu_16.csv
 - maryland_edu_17.csv
 - maryland_edu_18.csv
 - maryland_edu_19.csv
 - maryland_edu_20.csv
 - maryland_edu_21.csv
 - maryland_edu_22.csv
 - maryland_edu_23.csv
 - mississippi_edu_16.csv
 - mississippi_edu_17.csv
 - mississippi_edu_18.csv
 - mississippi_edu_19.csv
 - mississippi_edu_20.csv
 - mississippi_edu_21.csv
 - mississippi_edu_22.csv
 - mississippi_edu_23.csv
 - nc_edu_15.csv
 - nc_edu_16.csv
 - nc_edu_17.csv
 - nc_edu_18.csv
 - nc_edu_19.csv
 - nc_edu_20.csv
 - nc_edu_21.csv
 - nc_edu_22.csv
 - nc_edu_23.csv
 - ny_edu_15.csv
 - ny_edu_16.csv
 - ny_edu_17.csv
 - ny_edu_18.csv
 - ny_edu_19.csv
 - ny_edu_20.csv
 - ny_edu_21.csv
 - ny_edu_22.csv
 - ny_edu_23.csv
 - ohio_edu_15.csv
 - ohio_edu_16.csv
 - ohio_edu_17.csv
 - ohio_edu_18.csv
 - ohio_edu_19.csv
 - ohio_edu_20.csv
 - ohio_edu_21.csv
 - ohio_edu_22.csv
 - ohio_edu_23.csv
 - penn_edu_15.csv
 - penn_edu_16.csv
 - penn_edu_17.csv
 - penn_edu_18.csv
 - penn_edu_19.csv
 - penn_edu_20.csv
 - penn_edu_21.csv
 - penn_edu_22.csv
 - penn_edu_23.csv
 - raw_education.csv
 - sc_16.csv
 - sc_17.csv
 - sc_18.csv
 - sc_19.csv
 - sc_20.csv
 - sc_21.csv
 - sc_22.csv
 - sc_23.csv
 - tn_edu_15.csv
 - tn_edu_16.csv
 - tn_edu_17.csv
 - tn_edu_18.csv
 - tn_edu_19.csv
 - tn_edu_20.csv
 - tn_edu_21.csv
 - tn_edu_22.csv
 - tn_edu_23.csv
 - vir_edu_15.csv
 - vir_edu_16.csv
 - vir_edu_17.csv
 - vir_edu_18.csv
 - vir_edu_19.csv
 - vir_edu_20.csv
 - vir_edu_21.csv
 - vir_edu_22.csv
 - vir_edu_23.csv
 - wvir_edu_15.csv
 - wvir_edu_16.csv
 - wvir_edu_17.csv
 - wvir_edu_18.csv
 - wvir_edu_19.csv
 - wvir_edu_20.csv
 - wvir_edu_21.csv
 - wvir_edu_22.csv
 - wvir_edu_23.csv
           GEO_ID                     NAME  \
0       Geography     Geographic Area Name
1  0500000US01001  Autauga County, Alabama
2  0500000US01003  Baldwin County, Alabama
3  0500000US01005  Barbour County, Alabama
4  0500000US01007     Bibb County, Alabama

                               S1501_C01_001E  \
0  Total!!Estimate!!Population 18 to 24 years
1                                        4858
2                                       14479
3                                        2386
4                                        2056

                                      S1501_C01_001M  \
0  Total!!Margin of Error!!Population 18 to 24 years
1                                                171
2                                                313
3                                                 86
4                                                157

                                 S1501_C02_001E  \
0  Percent!!Estimate!!Population 18 to 24 years
1                                           (X)
2                                           (X)
3                                           (X)
4                                           (X)

                                      S1501_C02_001M  \
0  Percent!!Margin of Error!!Population 18 to 24 ...
1                                                (X)
2                                                (X)
3                                                (X)
4                                                (X)

                               S1501_C03_001E  \
0  Males!!Estimate!!Population 18 to 24 years
1                                        2519
2                                        7430
3                                        1404
4                                        1132

                                      S1501_C03_001M  \
0  Males!!Margin of Error!!Population 18 to 24 years
1                                                168
2                                                220
3                                                 61
4                                                134

                                      S1501_C04_001E  \
0  Percent Males!!Estimate!!Population 18 to 24 y...
1                                                (X)
2                                                (X)
3                                                (X)
4                                                (X)

                                      S1501_C04_001M  ...  \
0  Percent Males!!Margin of Error!!Population 18 ...  ...
1                                                (X)  ...
2                                                (X)  ...
3                                                (X)  ...
4                                                (X)  ...

                                      S1501_C03_064E  \
0  Males!!Estimate!!MEDIAN EARNINGS IN THE PAST 1...
1                                              76576
2                                              80038
3                                              55341
4                                              52321

                                      S1501_C03_064M  \
0  Males!!Margin of Error!!MEDIAN EARNINGS IN THE...
1                                               7260
2                                              10011
3                                              45677
4                                              27741

                                      S1501_C04_064E  \
0  Percent Males!!Estimate!!MEDIAN EARNINGS IN TH...
1                                                (X)
2                                                (X)
3                                                (X)
4                                                (X)

                                      S1501_C04_064M  \
0  Percent Males!!Margin of Error!!MEDIAN EARNING...
1                                                (X)
2                                                (X)
3                                                (X)
4                                                (X)

                                      S1501_C05_064E  \
0  Females!!Estimate!!MEDIAN EARNINGS IN THE PAST...
1                                              46293
2                                              48693
3                                              50614
4                                              47500

                                      S1501_C05_064M  \
0  Females!!Margin of Error!!MEDIAN EARNINGS IN T...
1                                               5058
2                                               5396
3                                               2923
4                                               7875

                                      S1501_C06_064E  \
0  Percent Females!!Estimate!!MEDIAN EARNINGS IN ...
1                                                (X)
2                                                (X)
3                                                (X)
4                                                (X)

                                      S1501_C06_064M Unnamed: 770 year
0  Percent Females!!Margin of Error!!MEDIAN EARNI...          NaN   15
1                                                (X)          NaN   15
2                                                (X)          NaN   15
3                                                (X)          NaN   15
4                                                (X)          NaN   15

[5 rows x 772 columns]

In [82]:
edu_df.head()

,GEO_ID,NAME,S1501_C01_001E,S1501_C01_001M,S1501_C02_001E,S1501_C02_001M,S1501_C03_001E,S1501_C03_001M,S1501_C04_001E,S1501_C04_001M,...,S1501_C03_064E,S1501_C03_064M,S1501_C04_064E,S1501_C04_064M,S1501_C05_064E,S1501_C05_064M,S1501_C06_064E,S1501_C06_064M,Unnamed: 770,year
0,Geography,Geographic Area Name,Total!!Estimate!!Population 18 to 24 years,Total!!Margin of Error!!Population 18 to 24 years,Percent!!Estimate!!Population 18 to 24 years,Percent!!Margin of Error!!Population 18 to 24 ...,Males!!Estimate!!Population 18 to 24 years,Males!!Margin of Error!!Population 18 to 24 years,Percent Males!!Estimate!!Population 18 to 24 y...,Percent Males!!Margin of Error!!Population 18 ...,...,Males!!Estimate!!MEDIAN EARNINGS IN THE PAST 1...,Males!!Margin of Error!!MEDIAN EARNINGS IN THE...,Percent Males!!Estimate!!MEDIAN EARNINGS IN TH...,Percent Males!!Margin of Error!!MEDIAN EARNING...,Females!!Estimate!!MEDIAN EARNINGS IN THE PAST...,Females!!Margin of Error!!MEDIAN EARNINGS IN T...,Percent Females!!Estimate!!MEDIAN EARNINGS IN ...,Percent Females!!Margin of Error!!MEDIAN EARNI...,NaN,15
1,0500000US01001,"Autauga County, Alabama",4858,171,(X),(X),2519,168,(X),(X),...,76576,7260,(X),(X),46293,5058,(X),(X),NaN,15
2,0500000US01003,"Baldwin County, Alabama",14479,313,(X),(X),7430,220,(X),(X),...,80038,10011,(X),(X),48693,5396,(X),(X),NaN,15
3,0500000US01005,"Barbour County, Alabama",2386,86,(X),(X),1404,61,(X),(X),...,55341,45677,(X),(X),50614,2923,(X),(X),NaN,15
4,0500000US01007,"Bibb County, Alabama",2056,157,(X),(X),1132,134,(X),(X),...,52321,27741,(X),(X),47500,7875,(X),(X),NaN,15

In [83]:
os.chdir(r"c:\Atharv\Git\fahe\filtered")
print(os.getcwd())

c:\Atharv\Git\fahe\filtered

In [84]:
edu_df.to_csv("filtered_education.csv", index=False)

In [85]:
edu_df.head()

,GEO_ID,NAME,S1501_C01_001E,S1501_C01_001M,S1501_C02_001E,S1501_C02_001M,S1501_C03_001E,S1501_C03_001M,S1501_C04_001E,S1501_C04_001M,...,S1501_C03_064E,S1501_C03_064M,S1501_C04_064E,S1501_C04_064M,S1501_C05_064E,S1501_C05_064M,S1501_C06_064E,S1501_C06_064M,Unnamed: 770,year
0,Geography,Geographic Area Name,Total!!Estimate!!Population 18 to 24 years,Total!!Margin of Error!!Population 18 to 24 years,Percent!!Estimate!!Population 18 to 24 years,Percent!!Margin of Error!!Population 18 to 24 ...,Males!!Estimate!!Population 18 to 24 years,Males!!Margin of Error!!Population 18 to 24 years,Percent Males!!Estimate!!Population 18 to 24 y...,Percent Males!!Margin of Error!!Population 18 ...,...,Males!!Estimate!!MEDIAN EARNINGS IN THE PAST 1...,Males!!Margin of Error!!MEDIAN EARNINGS IN THE...,Percent Males!!Estimate!!MEDIAN EARNINGS IN TH...,Percent Males!!Margin of Error!!MEDIAN EARNING...,Females!!Estimate!!MEDIAN EARNINGS IN THE PAST...,Females!!Margin of Error!!MEDIAN EARNINGS IN T...,Percent Females!!Estimate!!MEDIAN EARNINGS IN ...,Percent Females!!Margin of Error!!MEDIAN EARNI...,NaN,15
1,0500000US01001,"Autauga County, Alabama",4858,171,(X),(X),2519,168,(X),(X),...,76576,7260,(X),(X),46293,5058,(X),(X),NaN,15
2,0500000US01003,"Baldwin County, Alabama",14479,313,(X),(X),7430,220,(X),(X),...,80038,10011,(X),(X),48693,5396,(X),(X),NaN,15
3,0500000US01005,"Barbour County, Alabama",2386,86,(X),(X),1404,61,(X),(X),...,55341,45677,(X),(X),50614,2923,(X),(X),NaN,15
4,0500000US01007,"Bibb County, Alabama",2056,157,(X),(X),1132,134,(X),(X),...,52321,27741,(X),(X),47500,7875,(X),(X),NaN,15

In [86]:
# Split NAME column into County and State
edu_df[['County', 'State']] = edu_df['NAME'].str.split(',', expand=True)

# Clean up extra spaces
edu_df['County'] = edu_df['County'].str.strip()
edu_df['State'] = edu_df['State'].str.strip()

# Remove the word "County" from County column
edu_df['County'] = edu_df['County'].str.replace('County', '', regex=False).str.strip()

# Reorder columns: GEO_ID, year, County, State, then the rest
cols = edu_df.columns.tolist()

# Ensure order
new_order = ['GEO_ID','year', 'County', 'State'] + [col for col in cols if col not in ['GEO_ID', 'year', 'County', 'State']]

df_all = edu_df[new_order]
df_all = df_all.drop('NAME', axis=1)

C:\Users\athar\AppData\Local\Temp\ipykernel_7316\4033153363.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  edu_df[['County', 'State']] = edu_df['NAME'].str.split(',', expand=True)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\4033153363.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  edu_df[['County', 'State']] = edu_df['NAME'].str.split(',', expand=True)

In [87]:
# List of columns to keep
keep = [
    "GEO_ID", "NAME", "State", "County", "year",   
    "S1501_C01_059E",   # Median earnings (headline for education table)
]

# Filter to the columns that exist, then rename
existing = [c for c in keep if c in df_all.columns]

# Dictionary for renaming columns
renamed = {
    "S1501_C01_059E": "Total Median Earnings",
}

In [88]:
# Create the output DataFrame with existing columns and renamed
df_out = df_all[existing].rename(columns=renamed)

In [89]:
df_out.head()

,GEO_ID,State,County,year,Total Median Earnings
0,Geography,None,Geographic Area Name,15,Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 1...
1,0500000US01001,Alabama,Autauga,15,35422
2,0500000US01003,Alabama,Baldwin,15,31531
3,0500000US01005,Alabama,Barbour,15,25941
4,0500000US01007,Alabama,Bibb,15,29113

In [90]:
# Replace all occurrences of '(X)' with None (null in pandas)
df_out = df_out.replace('(X)', None)

In [91]:
df_out.columns = [col.lower().replace(' ', '_') for col in df_out.columns]

In [92]:
# Extract only digits from year column, drop bad text
df_out["year"] = df_out["year"].astype(str).str.extract(r"(\d+)")

# Convert to integer
df_out["year"] = pd.to_numeric(df_out["year"], errors="coerce").astype("Int64")

# Build mapping dynamically for 2-digit years, skipping NA values
year_map = {y: 2000 + y for y in df_out["year"].unique() 
            if pd.notna(y) and y < 100}

# Apply replacement
df_out["year"] = df_out["year"].replace(year_map)


print(year_map)                # e.g. {15: 2015, 16: 2016}
print(df_out["year"].unique()) # should show full 4-digit years

{np.int64(15): np.int64(2015), np.int64(16): np.int64(2016), np.int64(17): np.int64(2017), np.int64(18): np.int64(2018), np.int64(19): np.int64(2019), np.int64(20): np.int64(2020), np.int64(21): np.int64(2021), np.int64(22): np.int64(2022), np.int64(23): np.int64(2023)}
<IntegerArray>
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, <NA>]
Length: 10, dtype: Int64

In [93]:
df_out.head()

,geo_id,state,county,year,total_median_earnings
0,Geography,None,Geographic Area Name,2015,Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 1...
1,0500000US01001,Alabama,Autauga,2015,35422
2,0500000US01003,Alabama,Baldwin,2015,31531
3,0500000US01005,Alabama,Barbour,2015,25941
4,0500000US01007,Alabama,Bibb,2015,29113

In [94]:
print(os.getcwd())

c:\Atharv\Git\fahe\filtered

In [95]:
os.chdir(r"c:\Atharv\Git\fahe")
print(os.getcwd())

c:\Atharv\Git\fahe

In [96]:
# Load the list of Appalachian counties
keep_county = pd.read_csv(r"raw\appalachian_counties.csv")

# Ensure GEO_ID is string
df_out["geo_id"] = df_out["geo_id"].astype(str)

# Extract last 5 digits of GEO_ID → county_fips
df_out["county_fips"] = df_out["geo_id"].str[-5:]

# Ensure county_fips in keep_county is string and zero-padded to 5 digits
keep_county["county_fips"] = keep_county["fips"].astype(str).str.zfill(5)

In [97]:
# Inner join: keep only rows that exist in both
df_education = df_out.merge(
    keep_county[["county_fips"]].drop_duplicates(),
    on="county_fips",
    how="inner"
)

In [98]:
df_education.head(10)

           geo_id    state    county  year total_median_earnings county_fips
0  0500000US01007  Alabama      Bibb  2015                 29113       01007
1  0500000US01009  Alabama    Blount  2015                 34549       01009
2  0500000US01015  Alabama   Calhoun  2015                 28449       01015
3  0500000US01017  Alabama  Chambers  2015                 28983       01017
4  0500000US01019  Alabama  Cherokee  2015                 30545       01019
5  0500000US01021  Alabama   Chilton  2015                 31580       01021
6  0500000US01027  Alabama      Clay  2015                 25756       01027
7  0500000US01029  Alabama  Cleburne  2015                 31240       01029
8  0500000US01033  Alabama   Colbert  2015                 31484       01033
9  0500000US01037  Alabama     Coosa  2015                  None       01037

In [99]:
# Filter df_education for Bibb county (case-insensitive, strip whitespace)
bibb_education = df_education[df_education['county'].str.strip().str.lower() == 'bibb']
print(bibb_education)

               geo_id    state county  year total_median_earnings county_fips
0      0500000US01007  Alabama   Bibb  2015                 29113       01007
423    0500000US01007  Alabama   Bibb  2015                 29113       01007
460    0500000US01007  Alabama   Bibb  2016                 30328       01007
883    0500000US01007  Alabama   Bibb  2016                 30328       01007
920    0500000US01007  Alabama   Bibb  2017                 31833       01007
1343   0500000US01007  Alabama   Bibb  2017                 31833       01007
1380   0500000US01007  Alabama   Bibb  2018                 32108       01007
1803   0500000US01007  Alabama   Bibb  2018                 32108       01007
1840   0500000US01007  Alabama   Bibb  2019                 28789       01007
2263   0500000US01007  Alabama   Bibb  2019                 28789       01007
2300   0500000US01007  Alabama   Bibb  2020                 33912       01007
2723   0500000US01007  Alabama   Bibb  2020                 33912       01007
2760   0500000US01007  Alabama   Bibb  2021                 32759       01007
3183   0500000US01007  Alabama   Bibb  2021                 32759       01007
3220   0500000US01007  Alabama   Bibb  2022                 32546       01007
3643   0500000US01007  Alabama   Bibb  2022                 32546       01007
3680   0500000US01007  Alabama   Bibb  2023                 34001       01007
4103   0500000US01007  Alabama   Bibb  2023                 34001       01007
6336   0500000US01007  Alabama   Bibb  <NA>                 29113       01007
6759   0500000US01007  Alabama   Bibb  <NA>                 29113       01007
6796   0500000US01007  Alabama   Bibb  <NA>                 30328       01007
7219   0500000US01007  Alabama   Bibb  <NA>                 30328       01007
7256   0500000US01007  Alabama   Bibb  <NA>                 31833       01007
7679   0500000US01007  Alabama   Bibb  <NA>                 31833       01007
7716   0500000US01007  Alabama   Bibb  <NA>                 32108       01007
8139   0500000US01007  Alabama   Bibb  <NA>                 32108       01007
8176   0500000US01007  Alabama   Bibb  <NA>                 28789       01007
8599   0500000US01007  Alabama   Bibb  <NA>                 28789       01007
8636   0500000US01007  Alabama   Bibb  <NA>                 33912       01007
9059   0500000US01007  Alabama   Bibb  <NA>                 33912       01007
9096   0500000US01007  Alabama   Bibb  <NA>                 32759       01007
9519   0500000US01007  Alabama   Bibb  <NA>                 32759       01007
9556   0500000US01007  Alabama   Bibb  <NA>                 32546       01007
9979   0500000US01007  Alabama   Bibb  <NA>                 32546       01007
10016  0500000US01007  Alabama   Bibb  <NA>                 34001       01007
10439  0500000US01007  Alabama   Bibb  <NA>                 34001       01007

In [100]:
df_education.tail()

,geo_id,state,county,year,total_median_earnings,county_fips
15155,0500000US54101,West Virginia,Webster,2023,34747,54101
15156,0500000US54103,West Virginia,Wetzel,2023,40660,54103
15157,0500000US54105,West Virginia,Wirt,2023,39136,54105
15158,0500000US54107,West Virginia,Wood,2023,42099,54107
15159,0500000US54109,West Virginia,Wyoming,2023,36815,54109

In [101]:
# Check for missing values in df_education
missing_summary = df_education.isnull().sum()
print("Missing values in df_education:")
print(missing_summary)

Missing values in df_education:
geo_id                      0
state                       0
county                      0
year                     7580
total_median_earnings     262
county_fips                 0
dtype: int64

In [102]:
# Remove duplicates
df_education = df_education.drop_duplicates(subset=["geo_id", "state", "county", "year", "total_median_earnings", "county_fips"])

In [103]:

df_education = df_education[df_education['year'].notna()]

In [104]:
print(df_education[df_education['county'].str.strip().str.lower() == 'bibb'])

              geo_id    state county  year total_median_earnings county_fips
0     0500000US01007  Alabama   Bibb  2015                 29113       01007
460   0500000US01007  Alabama   Bibb  2016                 30328       01007
883   0500000US01007  Alabama   Bibb  2016                 30328       01007
920   0500000US01007  Alabama   Bibb  2017                 31833       01007
1343  0500000US01007  Alabama   Bibb  2017                 31833       01007
1380  0500000US01007  Alabama   Bibb  2018                 32108       01007
1803  0500000US01007  Alabama   Bibb  2018                 32108       01007
1840  0500000US01007  Alabama   Bibb  2019                 28789       01007
2263  0500000US01007  Alabama   Bibb  2019                 28789       01007
2300  0500000US01007  Alabama   Bibb  2020                 33912       01007
2723  0500000US01007  Alabama   Bibb  2020                 33912       01007
2760  0500000US01007  Alabama   Bibb  2021                 32759       01007
3183  0500000US01007  Alabama   Bibb  2021                 32759       01007
3220  0500000US01007  Alabama   Bibb  2022                 32546       01007
3643  0500000US01007  Alabama   Bibb  2022                 32546       01007
3680  0500000US01007  Alabama   Bibb  2023                 34001       01007
4103  0500000US01007  Alabama   Bibb  2023                 34001       01007

In [105]:
# Check for missing values in df_education
missing_summary = df_education.isnull().sum()
print("Missing values in df_education:")
print(missing_summary)

Missing values in df_education:
geo_id                    0
state                     0
county                    0
year                      0
total_median_earnings    70
county_fips               0
dtype: int64

# Income

In [620]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [621]:
# Path to your Education folder (go one level up first)
folder_path = os.path.join("..", "raw", "Income")


# Find all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

dfs_income = []
for file in csv_files:
    # Extract year from filename (e.g., Education_2019.csv → 2019)
    year = os.path.splitext(os.path.basename(file))[0].split("_")[-1]
    
    df_income = pd.read_csv(file)
    df_income["year"] = year   # Add year column
    dfs_income.append(df_income)

# Combine all with year included
inc_df = pd.concat(dfs_income, ignore_index=True)


print(f"Found {len(csv_files)} CSV files:")
for file in csv_files:
    print(f" - {os.path.basename(file)}")


print(inc_df.head())

Found 118 CSV files:
 - alabama_income_15.csv
 - alabama_income_16.csv
 - alabama_income_17.csv
 - alabama_income_18.csv
 - alabama_income_19.csv
 - alabama_income_20.csv
 - alabama_income_21.csv
 - alabama_income_22.csv
 - alabama_income_23.csv
 - georgia_income_15.csv
 - georgia_income_16.csv
 - georgia_income_17.csv
 - georgia_income_18.csv
 - georgia_income_19.csv
 - georgia_income_20.csv
 - georgia_income_21.csv
 - georgia_income_22.csv
 - georgia_income_23.csv
 - kentucky_income_15.csv
 - kentucky_income_16.csv
 - kentucky_income_17.csv
 - kentucky_income_18.csv
 - kentucky_income_19.csv
 - kentucky_income_20.csv
 - kentucky_income_21.csv
 - kentucky_income_22.csv
 - kentucky_income_23.csv
 - maryland_income_15.csv
 - maryland_income_16.csv
 - maryland_income_17.csv
 - maryland_income_18.csv
 - maryland_income_19.csv
 - maryland_income_20.csv
 - maryland_income_21.csv
 - maryland_income_22.csv
 - maryland_income_23.csv
 - missippi_income_15.csv
 - missippi_income_16.csv
 - missippi_income_17.csv
 - missippi_income_18.csv
 - missippi_income_19 copy.csv
 - missippi_income_19.csv
 - missippi_income_20.csv
 - missippi_income_21.csv
 - missippi_income_22.csv
 - missippi_income_23.csv
 - nc_income_15.csv
 - nc_income_16.csv
 - nc_income_17.csv
 - nc_income_18.csv
 - nc_income_19.csv
 - nc_income_20.csv
 - nc_income_21.csv
 - nc_income_22.csv
 - nc_income_23.csv
 - ny_income_15.csv
 - ny_income_16.csv
 - ny_income_17.csv
 - ny_income_18.csv
 - ny_income_19.csv
 - ny_income_20.csv
 - ny_income_21.csv
 - ny_income_22.csv
 - ny_income_23.csv
 - ohio_income_15.csv
 - ohio_income_16.csv
 - ohio_income_17.csv
 - ohio_income_18.csv
 - ohio_income_19.csv
 - ohio_income_20.csv
 - ohio_income_21.csv
 - ohio_income_22.csv
 - ohio_income_23.csv
 - penn_income_15.csv
 - penn_income_16.csv
 - penn_income_17.csv
 - penn_income_18.csv
 - penn_income_19.csv
 - penn_income_20.csv
 - penn_income_21.csv
 - penn_income_22.csv
 - penn_income_23.csv
 - sc_income_15.csv
 - sc_income_16.csv
 - sc_income_17.csv
 - sc_income_18.csv
 - sc_income_19.csv
 - sc_income_20.csv
 - sc_income_21.csv
 - sc_income_22.csv
 - sc_income_23.csv
 - tn_income_15.csv
 - tn_income_16.csv
 - tn_income_17.csv
 - tn_income_18.csv
 - tn_income_19.csv
 - tn_income_20.csv
 - tn_income_21.csv
 - tn_income_22.csv
 - tn_income_23.csv
 - vir_income_15.csv
 - vir_income_16.csv
 - vir_income_17.csv
 - vir_income_18.csv
 - vir_income_19.csv
 - vir_income_20.csv
 - vir_income_21.csv
 - vir_income_22.csv
 - vir_income_23.csv
 - wvir_income_15.csv
 - wvir_income_16.csv
 - wvir_income_17.csv
 - wvir_income_18.csv
 - wvir_income_19.csv
 - wvir_income_20.csv
 - wvir_income_21.csv
 - wvir_income_22.csv
 - wvir_income_23.csv
           GEO_ID                     NAME S1901_C01_001E S1901_C01_001M  \
0  0500000US01001  Autauga County, Alabama          20396            413
1  0500000US01003  Baldwin County, Alabama          74104           1265
2  0500000US01005  Barbour County, Alabama           9222            272
3  0500000US01007     Bibb County, Alabama           7027            354
4  0500000US01009   Blount County, Alabama          20816            427

  S1901_C02_001E S1901_C02_001M S1901_C03_001E S1901_C03_001M S1901_C04_001E  \
0          14213            539          11436            534           6183
1          50276           1220          39968           1191          23828
2           6059            259           3991            223           3163
3           5296            359           4029            329           1731
4          15639            416          12373            470           5177

  S1901_C04_001M  ... S1901_C01_016E S1901_C01_016M S1901_C02_016E  \
0            578  ...            (X)            (X)            (X)
1           1070  ...            (X)            (X)            (X)
2            253  ...            (X)            (X)            (X)
3            236  ...            (X)            (X)            (X)
4            352  ...            (X)            (X)            (X)

  S1901_C02_016M S1901_C03_016E S1901_C03_016M S1901_C04_016E S1901_C04_016M  \
0            (X)            (X)            (X)           26.4            (X)
1            (X)            (X)            (X)           26.6            (X)
2            (X)            (X)            (X)           25.6            (X)
3            (X)            (X)            (X)           33.4            (X)
4            (X)            (X)            (X)           24.5            (X)

  year Unnamed: 130
0   15          NaN
1   15          NaN
2   15          NaN
3   15          NaN
4   15          NaN

[5 rows x 132 columns]

In [622]:
inc_df.head()

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C02_001E,S1901_C02_001M,S1901_C03_001E,S1901_C03_001M,S1901_C04_001E,S1901_C04_001M,...,S1901_C01_016E,S1901_C01_016M,S1901_C02_016E,S1901_C02_016M,S1901_C03_016E,S1901_C03_016M,S1901_C04_016E,S1901_C04_016M,year,Unnamed: 130
0,0500000US01001,"Autauga County, Alabama",20396,413,14213,539,11436,534,6183,578,...,(X),(X),(X),(X),(X),(X),26.4,(X),15,NaN
1,0500000US01003,"Baldwin County, Alabama",74104,1265,50276,1220,39968,1191,23828,1070,...,(X),(X),(X),(X),(X),(X),26.6,(X),15,NaN
2,0500000US01005,"Barbour County, Alabama",9222,272,6059,259,3991,223,3163,253,...,(X),(X),(X),(X),(X),(X),25.6,(X),15,NaN
3,0500000US01007,"Bibb County, Alabama",7027,354,5296,359,4029,329,1731,236,...,(X),(X),(X),(X),(X),(X),33.4,(X),15,NaN
4,0500000US01009,"Blount County, Alabama",20816,427,15639,416,12373,470,5177,352,...,(X),(X),(X),(X),(X),(X),24.5,(X),15,NaN

In [623]:
os.chdir(r"c:\Atharv\Git\fahe\filtered")
print(os.getcwd())

c:\Atharv\Git\fahe\filtered

In [624]:
inc_df.to_csv("filtered_income.csv", index=False)

In [625]:
# Split NAME column into County and State
inc_df[['County', 'State']] = inc_df['NAME'].str.split(',', expand=True)

# Clean up extra spaces
inc_df['County'] = inc_df['County'].str.strip()
inc_df['State'] = inc_df['State'].str.strip()

# Remove the word "County" from County column
inc_df['County'] = inc_df['County'].str.replace('County', '', regex=False).str.strip()

# Reorder columns: GEO_ID, year, County, State, then the rest
cols = inc_df.columns.tolist()

# Ensure order
new_order = ['GEO_ID','year', 'County', 'State'] + [col for col in cols if col not in ['GEO_ID', 'year', 'County', 'State']]

inc_df = inc_df[new_order]
inc_df = inc_df.drop('NAME', axis=1)

C:\Users\athar\AppData\Local\Temp\ipykernel_7316\4175630603.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  inc_df[['County', 'State']] = inc_df['NAME'].str.split(',', expand=True)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\4175630603.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  inc_df[['County', 'State']] = inc_df['NAME'].str.split(',', expand=True)

In [626]:
# List of columns to keep
keep = [
    "GEO_ID", "NAME", "State", "County", "year",   
    "S1901_C01_001E",      # total households
    "S1901_C01_012E"       # mean household income (avg per household)
]

# Filter to the columns that exist, then rename
existing = [c for c in keep if c in inc_df.columns]

# Dictionary for renaming columns
renamed = {
    "S1901_C01_001E": "Number of households",
    "S1901_C01_012E": "Average income per household",
}
# Create the output DataFrame with existing columns and renamed
inc_df = inc_df[existing].rename(columns=renamed)

In [627]:
# Replace all occurrences of '(X)' with None (null in pandas)
inc_df = inc_df.replace('(X)', None)

inc_df.columns = [col.lower().replace(' ', '_') for col in inc_df.columns]

In [628]:
# Extract only digits from year column, drop bad text
inc_df["year"] = inc_df["year"].astype(str).str.extract(r"(\d+)")

# Convert to integer
inc_df["year"] = inc_df["year"].astype(int)

# Build mapping dynamically for 2-digit years
year_map = {y: 2000 + y for y in inc_df["year"].unique() if y < 100}

# Apply replacement
inc_df["year"] = inc_df["year"].replace(year_map)


print(year_map)                # e.g. {15: 2015, 16: 2016}
print(inc_df["year"].unique()) # should show full 4-digit years

{np.int64(15): np.int64(2015), np.int64(16): np.int64(2016), np.int64(17): np.int64(2017), np.int64(18): np.int64(2018), np.int64(19): np.int64(2019), np.int64(20): np.int64(2020), np.int64(21): np.int64(2021), np.int64(22): np.int64(2022), np.int64(23): np.int64(2023)}
[2015 2016 2017 2018 2019 2020 2021 2022 2023]

In [629]:
os.chdir(r"c:\Atharv\Git\fahe")
print(os.getcwd())

c:\Atharv\Git\fahe

In [630]:
# Load the list of Appalachian counties
keep_county = pd.read_csv(r"raw\appalachian_counties.csv")

# Ensure GEO_ID is string
inc_df["geo_id"] = inc_df["geo_id"].astype(str)

# Extract last 5 digits of GEO_ID → county_fips
inc_df["county_fips"] = inc_df["geo_id"].str[-5:]

# Ensure county_fips in keep_county is string and zero-padded to 5 digits
keep_county["county_fips"] = keep_county["fips"].astype(str).str.zfill(5)

In [631]:
# Inner join: keep only rows that exist in both
df_income = inc_df.merge(
    keep_county[["county_fips"]].drop_duplicates(),
    on="county_fips",
    how="inner"
)

df_income.head()

,geo_id,state,county,year,number_of_households,average_income_per_household,county_fips
0,0500000US01007,Alabama,Bibb,2015,7027,38678,01007
1,0500000US01009,Alabama,Blount,2015,20816,45813,01009
2,0500000US01015,Alabama,Calhoun,2015,45154,41703,01015
3,0500000US01017,Alabama,Chambers,2015,13787,34177,01017
4,0500000US01019,Alabama,Cherokee,2015,11278,36296,01019

In [632]:

# Check for missing values in df_income
missing_counts = df_income.isnull().sum()
print("Missing values per column in df_income:")
print(missing_counts)

Missing values per column in df_income:
geo_id                          0
state                           0
county                          0
year                            0
number_of_households            0
average_income_per_household    0
county_fips                     0
dtype: int64

In [633]:
df_income.dtypes

geo_id                          object
state                           object
county                          object
year                             int64
number_of_households            object
average_income_per_household    object
county_fips                     object
dtype: object

# Poverty

In [132]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [133]:
# Path to your Education folder (go one level up first)
folder_path = os.path.join("..", "raw", "Poverty")


# Find all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

dfs_poverty = []
for file in csv_files:
    # Extract year from filename (e.g., Education_2019.csv → 2019)
    year = os.path.splitext(os.path.basename(file))[0].split("_")[-1]
    
    df_poverty = pd.read_csv(file)
    df_poverty["year"] = year   # Add year column
    dfs_poverty.append(df_poverty)

# Combine all with year included
pov_df = pd.concat(dfs_poverty, ignore_index=True)


print(f"Found {len(csv_files)} CSV files:")
for file in csv_files:
    print(f" - {os.path.basename(file)}")


print(pov_df.head())

C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,86,87,88,89,92,93,94,95,98,99,100,101,104,105,106,107,110,111,112,113,116,117,118,119,122,123,124,125,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,188,189,190,191,194,195,196,197,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,230,231,236,237,242,243,248,249,254,255,260,261,266,267,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,296,297,298,299,302,303,304,305,308,309,310,311,314,315,316,317,320,321,322,323,326,327,328,329,332,333,334,335,336,337,338,339,340,341,350,351,352,353,354,355,356,357,358,359,362,363,364,365,366,367) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,86,87,88,89,92,93,94,95,98,99,100,101,104,105,106,107,110,111,112,113,116,117,118,119,122,123,124,125,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,188,189,190,191,194,195,196,197,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,230,231,236,237,242,243,248,249,254,255,260,261,266,267,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,296,297,298,299,302,303,304,305,308,309,310,311,314,315,316,317,320,321,322,323,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,350,351,352,353,354,355,356,357,358,359,362,363,364,365,366,367) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,240,241,242,243,244,245,246,247,248,249,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,312,313,314,315,316,317,318,319,336,337,338,339,340,341,362,363,366,367) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,180,181,184,185,188,189,192,193,196,197,200,201,204,205,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,248,249,252,253,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,304,305,306,307,308,309,310,311,312,313,314,315,316,317,320,321,324,325,328,329,332,333,336,337,340,341,344,345,348,349,350,351,356,357,358,359,360,361,364,365,366,367) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,286,287,288,289,290,291,292,293,294,295,298,299,300,301,302,303,304,305,312,313,314,315,316,317,318,319,336,337,338,339,340,341,356,357,362,363,366,367) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,286,287,288,289,290,291,292,293,294,295,298,299,300,301,302,303,304,305,312,313,314,315,316,317,318,319,336,337,338,339,362,363,366,367) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,292,293,294,295,296,297,302,303,304,305,306,307,308,309,316,317,318,319,320,321,322,323,340,341,342,343,344,345,372,373) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,242,243,244,245,246,247,248,249,250,251,252,253,254,255,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,292,293,294,295,296,297,298,299,302,303,304,305,306,307,308,309,316,317,318,319,320,321,322,323,340,341,342,343,344,345,372,373) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)
C:\Users\athar\AppData\Local\Temp\ipykernel_7316\1747080799.py:13: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,242,243,244,245,246,247,248,249,250,251,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,292,293,294,295,296,297,298,299,302,303,304,305,306,307,308,309,316,317,318,319,320,321,322,323,340,341,372,373) have mixed types. Specify dtype option on import or set low_memory=False.
  df_poverty = pd.read_csv(file)

Found 117 CSV files:
 - alabama_poverty_15.csv
 - alabama_poverty_16.csv
 - alabama_poverty_17.csv
 - alabama_poverty_18.csv
 - alabama_poverty_19.csv
 - alabama_poverty_20.csv
 - alabama_poverty_21.csv
 - alabama_poverty_22.csv
 - alabama_poverty_23.csv
 - georgia_poverty_15.csv
 - georgia_poverty_16.csv
 - georgia_poverty_17.csv
 - georgia_poverty_18.csv
 - georgia_poverty_19.csv
 - georgia_poverty_20.csv
 - georgia_poverty_21.csv
 - georgia_poverty_22.csv
 - georgia_poverty_23.csv
 - kentucky_poverty_15.csv
 - kentucky_poverty_16.csv
 - kentucky_poverty_17.csv
 - kentucky_poverty_18.csv
 - kentucky_poverty_19.csv
 - kentucky_poverty_20.csv
 - kentucky_poverty_21.csv
 - kentucky_poverty_22.csv
 - kentucky_poverty_23.csv
 - maryland_poverty_15.csv
 - maryland_poverty_16.csv
 - maryland_poverty_17.csv
 - maryland_poverty_18.csv
 - maryland_poverty_19.csv
 - maryland_poverty_20.csv
 - maryland_poverty_21.csv
 - maryland_poverty_22.csv
 - maryland_poverty_23.csv
 - missippi_poverty_15.csv
 - missippi_poverty_16.csv
 - missippi_poverty_17.csv
 - missippi_poverty_18.csv
 - missippi_poverty_19.csv
 - missippi_poverty_20.csv
 - missippi_poverty_21.csv
 - missippi_poverty_22.csv
 - missippi_poverty_23.csv
 - nc_poverty_15.csv
 - nc_poverty_16.csv
 - nc_poverty_17.csv
 - nc_poverty_18.csv
 - nc_poverty_19.csv
 - nc_poverty_20.csv
 - nc_poverty_21.csv
 - nc_poverty_22.csv
 - nc_poverty_23.csv
 - ny_poverty_15.csv
 - ny_poverty_16.csv
 - ny_poverty_17.csv
 - ny_poverty_18.csv
 - ny_poverty_19.csv
 - ny_poverty_20.csv
 - ny_poverty_21.csv
 - ny_poverty_22.csv
 - ny_poverty_23.csv
 - ohio_poverty_15.csv
 - ohio_poverty_16.csv
 - ohio_poverty_17.csv
 - ohio_poverty_18.csv
 - ohio_poverty_19.csv
 - ohio_poverty_20.csv
 - ohio_poverty_21.csv
 - ohio_poverty_22.csv
 - ohio_poverty_23.csv
 - penn_poverty_15.csv
 - penn_poverty_16.csv
 - penn_poverty_17.csv
 - penn_poverty_18.csv
 - penn_poverty_19.csv
 - penn_poverty_20.csv
 - penn_poverty_21.csv
 - penn_poverty_22.csv
 - penn_poverty_23.csv
 - sc_poverty_15.csv
 - sc_poverty_16.csv
 - sc_poverty_17.csv
 - sc_poverty_18.csv
 - sc_poverty_19.csv
 - sc_poverty_20.csv
 - sc_poverty_21.csv
 - sc_poverty_22.csv
 - sc_poverty_23.csv
 - tn_poverty_15.csv
 - tn_poverty_16.csv
 - tn_poverty_17.csv
 - tn_poverty_18.csv
 - tn_poverty_19.csv
 - tn_poverty_20.csv
 - tn_poverty_21.csv
 - tn_poverty_22.csv
 - tn_poverty_23.csv
 - vir_poverty_15.csv
 - vir_poverty_16.csv
 - vir_poverty_17.csv
 - vir_poverty_18.csv
 - vir_poverty_19.csv
 - vir_poverty_20.csv
 - vir_poverty_21.csv
 - vir_poverty_22.csv
 - vir_poverty_23.csv
 - wvir_poverty_15.csv
 - wvir_poverty_16.csv
 - wvir_poverty_17.csv
 - wvir_poverty_18.csv
 - wvir_poverty_19.csv
 - wvir_poverty_20.csv
 - wvir_poverty_21.csv
 - wvir_poverty_22.csv
 - wvir_poverty_23.csv
           GEO_ID                     NAME  \
0       Geography     Geographic Area Name
1  0500000US01001  Autauga County, Alabama
2  0500000US01003  Baldwin County, Alabama
3  0500000US01005  Barbour County, Alabama
4  0500000US01007     Bibb County, Alabama

                                      S1701_C01_001E  \
0  Total!!Estimate!!Population for whom poverty s...
1                                              54793
2                                             192355
3                                              24024
4                                              20767

                                      S1701_C01_001M  \
0  Total!!Margin of Error!!Population for whom po...
1                                                152
2                                                441
3                                                310
4                                                216

                                      S1701_C02_001E  \
0  Below poverty level!!Estimate!!Population for ...
1                                               7057
2                                              25798
3                                               6421
4                                               3488

                                      S1701_C02_001M  \
0  Below poverty level!!Margin of Error!!Populati...
1                                               1134
2                                               2300
3                                                645
4                                                807

                                      S1701_C03_001E  \
0  Percent below poverty level!!Estimate!!Populat...
1                                               12.9
2                                               13.4
3                                               26.7
4                                               16.8

                                      S1701_C03_001M  \
0  Percent below poverty level!!Margin of Error!!...
1                                                2.1
2                                                1.2
3                                                2.7
4                                                3.9

                         S1701_C01_002E  \
0  Total!!Estimate!!AGE!!Under 18 years
1                                 13967
2                                 43247
3                                  5702
4                                  4874

                                S1701_C01_002M  ...  \
0  Total!!Margin of Error!!AGE!!Under 18 years  ...
1                                           74  ...
2                                          233  ...
3                                           30  ...
4                                          125  ...

                                      S1701_C03_061M Unnamed: 368 year  \
0  Percent below poverty level!!Margin of Error!!...          NaN   15
1                                                7.4          NaN   15
2                                                3.8          NaN   15
3                                                6.3          NaN   15
4                                                8.9          NaN   15

  S1701_C01_062E S1701_C01_062M S1701_C02_062E S1701_C02_062M S1701_C03_062E  \
0            NaN            NaN            NaN            NaN            NaN
1            NaN            NaN            NaN            NaN            NaN
2            NaN            NaN            NaN            NaN            NaN
3            NaN            NaN            NaN            NaN            NaN
4            NaN            NaN            NaN            NaN            NaN

  S1701_C03_062M Unnamed: 374
0            NaN          NaN
1            NaN          NaN
2            NaN          NaN
3            NaN          NaN
4            NaN          NaN

[5 rows x 377 columns]

In [134]:
pov_df.head()

,GEO_ID,NAME,S1701_C01_001E,S1701_C01_001M,S1701_C02_001E,S1701_C02_001M,S1701_C03_001E,S1701_C03_001M,S1701_C01_002E,S1701_C01_002M,...,S1701_C03_061M,Unnamed: 368,year,S1701_C01_062E,S1701_C01_062M,S1701_C02_062E,S1701_C02_062M,S1701_C03_062E,S1701_C03_062M,Unnamed: 374
0,Geography,Geographic Area Name,Total!!Estimate!!Population for whom poverty s...,Total!!Margin of Error!!Population for whom po...,Below poverty level!!Estimate!!Population for ...,Below poverty level!!Margin of Error!!Populati...,Percent below poverty level!!Estimate!!Populat...,Percent below poverty level!!Margin of Error!!...,Total!!Estimate!!AGE!!Under 18 years,Total!!Margin of Error!!AGE!!Under 18 years,...,Percent below poverty level!!Margin of Error!!...,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0500000US01001,"Autauga County, Alabama",54793,152,7057,1134,12.9,2.1,13967,74,...,7.4,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0500000US01003,"Baldwin County, Alabama",192355,441,25798,2300,13.4,1.2,43247,233,...,3.8,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0500000US01005,"Barbour County, Alabama",24024,310,6421,645,26.7,2.7,5702,30,...,6.3,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0500000US01007,"Bibb County, Alabama",20767,216,3488,807,16.8,3.9,4874,125,...,8.9,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
os.chdir(r"c:\Atharv\Git\fahe\filtered")
print(os.getcwd())

c:\Atharv\Git\fahe\filtered

In [136]:
pov_df.to_csv("filtered_poverty.csv", index=False)

In [137]:
# Delete row at index 0
pov_df = pov_df.drop(0)
# Reset index after deletion
pov_df = pov_df.reset_index(drop=True)

In [138]:
# Split NAME column into County and State
pov_df[['County', 'State']] = pov_df['NAME'].str.split(',', expand=True)

# Clean up extra spaces
pov_df['County'] = pov_df['County'].str.strip()
pov_df['State'] = pov_df['State'].str.strip()

# Remove the word "County" from County column
pov_df['County'] = pov_df['County'].str.replace('County', '', regex=False).str.strip()

# Reorder columns: GEO_ID, year, County, State, then the rest
cols = pov_df.columns.tolist()

# Ensure order
new_order = ['GEO_ID','year', 'County', 'State'] + [col for col in cols if col not in ['GEO_ID', 'year', 'County', 'State']]

pov_df = pov_df[new_order]
pov_df = pov_df.drop('NAME', axis=1)

In [139]:
# List of columns to keep
keep = [
    "GEO_ID", "NAME", "State", "County", "year",   
    "S1701_C01_001E",      # Total Population
    "S1701_C02_001E",       # Population Below Poverty
    "S1701_C03_001E",       #Percent Below Poverty
    "S1701_C01_023E",       #Less Than High School Graduate
    "S1701_C01_026E",       #Bachelor's degree or higher
]

# Filter to the columns that exist, then rename
existing = [c for c in keep if c in pov_df.columns]

# Dictionary for renaming columns
renamed = {
    "S1701_C01_001E": "Total Population",
    "S1701_C02_001E": "Population Below Poverty",     
    "S1701_C03_001E": "Population Below Poverty Percent",      
    "S1701_C01_023E": "Adults 25 and Older Less Than High School Graduate",       
    "S1701_C01_026E": "Adults 25 and Older with Bachelor's degree or higher",              
}
# Create the output DataFrame with existing columns and renamed
pov_df = pov_df[existing].rename(columns=renamed)

In [140]:
# Calculating percent columns (value / Population Below Poverty) * 100
percent_cols = ["Adults 25 and Older Less Than High School Graduate Percent", "Adults 25 and Older with Bachelor's degree or higher Percent"]
existing_percent_cols = [col for col in percent_cols if col in pov_df.columns]
other_cols = [col for col in pov_df.columns if col not in existing_percent_cols]
pov_df = pov_df[existing_percent_cols + other_cols]


def insert_after(df, after_col, new_col, values):
    cols = list(df.columns)
    if after_col in cols:
        idx = cols.index(after_col) + 1
 
        if new_col in cols:
            cols.remove(new_col)
        cols = cols[:idx] + [new_col] + cols[idx:]
        df[new_col] = values
        df = df[cols]
    else:
        df[new_col] = values
    return df

# Incomplete High School Graduates (Percent)
if "Adults 25 and Older Less Than High School Graduate" in pov_df.columns and "Total Population" in pov_df.columns:
    percent = (
        pd.to_numeric(pov_df["Adults 25 and Older Less Than High School Graduate"], errors="coerce") /
        pd.to_numeric(pov_df["Total Population"], errors="coerce")
    ) * 100
    percent = percent.round(1)
    pov_df = insert_after(
        pov_df,
        "Adults 25 and Older Less Than High School Graduate",
        "Adults 25 and Older Less Than High School Graduate Percent",
        percent
    )

# Bachelor's degree or higher (Percent)
if "Adults 25 and Older with Bachelor's degree or higher" in pov_df.columns and "Total Population" in pov_df.columns:
    percent = (
        pd.to_numeric(pov_df["Adults 25 and Older with Bachelor's degree or higher"], errors="coerce") /
        pd.to_numeric(pov_df["Total Population"], errors="coerce")
    ) * 100
    percent = percent.round(1)
    pov_df = insert_after(
        pov_df,
        "Adults 25 and Older with Bachelor's degree or higher",
        "Adults 25 and Older with Bachelor's degree or higher Percent",
        percent
    )

In [141]:
# Replace all occurrences of '(X)' with None (null in pandas)
pov_df = pov_df.replace('(X)', None)

pov_df.columns = [col.lower().replace(' ', '_') for col in pov_df.columns]


# Extract only digits from year column, drop bad text
pov_df["year"] = pov_df["year"].astype(str).str.extract(r"(\d+)")

# Convert to integer
pov_df["year"] = pov_df["year"].astype(int)

# Build mapping dynamically for 2-digit years
year_map = {y: 2000 + y for y in pov_df["year"].unique() if y < 100}

# Apply replacement
pov_df["year"] = pov_df["year"].replace(year_map)


print(year_map)                # e.g. {15: 2015, 16: 2016}
print(pov_df["year"].unique()) # should show full 4-digit years

{np.int64(15): np.int64(2015), np.int64(16): np.int64(2016), np.int64(17): np.int64(2017), np.int64(18): np.int64(2018), np.int64(19): np.int64(2019), np.int64(20): np.int64(2020), np.int64(21): np.int64(2021), np.int64(22): np.int64(2022), np.int64(23): np.int64(2023)}
[2015 2016 2017 2018 2019 2020 2021 2022 2023]

In [142]:
os.chdir(r"c:\Atharv\Git\fahe")
print(os.getcwd()) 

# Load the list of Appalachian counties
keep_county = pd.read_csv(r"raw\appalachian_counties.csv")

# Ensure GEO_ID is string
pov_df["geo_id"] = pov_df["geo_id"].astype(str)

# Extract last 5 digits of GEO_ID → county_fips
pov_df["county_fips"] = pov_df["geo_id"].str[-5:]

# Ensure county_fips in keep_county is string and zero-padded to 5 digits
keep_county["county_fips"] = keep_county["fips"].astype(str).str.zfill(5)




# Inner join: keep only rows that exist in both
df_poverty = pov_df.merge(
    keep_county[["county_fips"]].drop_duplicates(),
    on="county_fips",
    how="inner"
)

df_poverty.head()

c:\Atharv\Git\fahe

,geo_id,state,county,year,total_population,population_below_poverty,population_below_poverty_percent,adults_25_and_older_less_than_high_school_graduate,adults_25_and_older_less_than_high_school_graduate_percent,adults_25_and_older_with_bachelor's_degree_or_higher,adults_25_and_older_with_bachelor's_degree_or_higher_percent,county_fips
0,0500000US01007,Alabama,Bibb,2015,20767,3488,16.8,2381,11.5,1657,8.0,01007
1,0500000US01009,Alabama,Blount,2015,57126,9552,16.7,8277,14.5,5060,8.9,01009
2,0500000US01015,Alabama,Calhoun,2015,113602,23325,20.5,14610,12.9,13756,12.1,01015
3,0500000US01017,Alabama,Chambers,2015,33687,7273,21.6,4906,14.6,2750,8.2,01017
4,0500000US01019,Alabama,Cherokee,2015,25575,4918,19.2,3719,14.5,2562,10.0,01019

In [143]:
# Check for missing values in each column of df_poverty
missing_counts = df_poverty.isnull().sum()
print("Missing values per column in df_poverty:")
print(missing_counts)

Missing values per column in df_poverty:
geo_id                                                          0
state                                                           0
county                                                          0
year                                                            0
total_population                                                0
population_below_poverty                                        0
population_below_poverty_percent                                0
adults_25_and_older_less_than_high_school_graduate              0
adults_25_and_older_less_than_high_school_graduate_percent      0
adults_25_and_older_with_bachelor's_degree_or_higher            0
adults_25_and_older_with_bachelor's_degree_or_higher_percent    0
county_fips                                                     0
dtype: int64

# Investment

In [168]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [169]:
# Path to your Education folder (go one level up first)
folder_path = os.path.join("..", "raw", "Investment")


# Find all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

dfs_investment = []
for file in csv_files:
    # Extract year from filename (e.g., Education_2019.csv → 2019)
    year = os.path.splitext(os.path.basename(file))[0].split("_")[-1]
    
    df_investment = pd.read_csv(file)
    df_investment["year"] = year   # Add year column
    dfs_investment.append(df_investment)

# Combine all with year included
inv_df = pd.concat(dfs_investment, ignore_index=True)


print(f"Found {len(csv_files)} CSV files:")
for file in csv_files:
    print(f" - {os.path.basename(file)}")


print(inv_df.head())

Found 11 CSV files:
 - 2015.csv
 - 2016.csv
 - 2017.csv
 - 2018.csv
 - 2019.csv
 - 2020.csv
 - 2021.csv
 - 2022.csv
 - 2023.csv
 - 2024.csv
 - 2025.csv
   fiscal_year state_name   county       zip_code  county_fips  \
0         2015    Alabama  Autauga  Not Available         1001
1         2015    Alabama  Autauga  Not Available         1001
2         2015    Alabama  Autauga  Not Available         1001
3         2015    Alabama  Autauga  Not Available         1001
4         2015    Alabama  Autauga  Not Available         1001

                                        funding_code           program_area  \
0  502 LOAN - GENERAL INTEREST SUBSIDY LOW & OTHE...  Single Family Housing
1  502 LOAN - GENERAL INTEREST SUBSIDY VERY LOW I...  Single Family Housing
2  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...  Single Family Housing
3  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...  Single Family Housing
4  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...  Single Family Housing

  investment_dollars  number_of_investments  year
0            130,000                      1  2015
1            169,800                      2  2015
2            147,959                      1  2015
3            962,764                      6  2015
4            121,428                      1  2015

In [170]:
os.chdir(r"c:\Atharv\Git\fahe\filtered")
print(os.getcwd())

c:\Atharv\Git\fahe\filtered

In [171]:
inv_df.to_csv("filtered_investment.csv", index=False)

In [172]:
inv_df.head()

,fiscal_year,state_name,county,zip_code,county_fips,funding_code,program_area,investment_dollars,number_of_investments,year
0,2015,Alabama,Autauga,Not Available,1001,502 LOAN - GENERAL INTEREST SUBSIDY LOW & OTHE...,Single Family Housing,"130,000",1,2015
1,2015,Alabama,Autauga,Not Available,1001,502 LOAN - GENERAL INTEREST SUBSIDY VERY LOW I...,Single Family Housing,"169,800",2,2015
2,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"147,959",1,2015
3,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"962,764",6,2015
4,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"121,428",1,2015

In [173]:
inv_df = inv_df.rename(columns={"state_name": "state"})

In [174]:
#group by
inv_df = inv_df.groupby(["year", "county", "state", "county_fips"])

In [175]:
inv_df.head()

,fiscal_year,state,county,zip_code,county_fips,funding_code,program_area,investment_dollars,number_of_investments,year
0,2015,Alabama,Autauga,Not Available,1001,502 LOAN - GENERAL INTEREST SUBSIDY LOW & OTHE...,Single Family Housing,"130,000",1,2015
1,2015,Alabama,Autauga,Not Available,1001,502 LOAN - GENERAL INTEREST SUBSIDY VERY LOW I...,Single Family Housing,"169,800",2,2015
2,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"147,959",1,2015
3,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"962,764",6,2015
4,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"121,428",1,2015
...,...,...,...,...,...,...,...,...,...,...
420750,2025,Wyoming,Washakie,Not Available,56043,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"249,494",1,2025
420751,2025,Wyoming,Washakie,Not Available,56043,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"257,575",1,2025
420752,2025,Wyoming,Washakie,Not Available,56043,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"118,500",1,2025
420753,2025,Wyoming,Weston,Not Available,56045,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"202,020",1,2025
420754,2025,Wyoming,Weston,Not Available,56045,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"320,201",2,2025

In [176]:
# List of columns to keep
keep = [
    "fiscal_year", "state", "county", "year", 
    "county_fips", "investment_dollars", "number_of_investments"   
]

In [177]:
# Apply the changes and view the cleaned DataFrame:
existing = [c for c in keep if c in inv_df.obj.columns]

print(inv_df.head())

        fiscal_year    state    county       zip_code  county_fips  \
0              2015  Alabama   Autauga  Not Available         1001
1              2015  Alabama   Autauga  Not Available         1001
2              2015  Alabama   Autauga  Not Available         1001
3              2015  Alabama   Autauga  Not Available         1001
4              2015  Alabama   Autauga  Not Available         1001
...             ...      ...       ...            ...          ...
420750         2025  Wyoming  Washakie  Not Available        56043
420751         2025  Wyoming  Washakie  Not Available        56043
420752         2025  Wyoming  Washakie  Not Available        56043
420753         2025  Wyoming    Weston  Not Available        56045
420754         2025  Wyoming    Weston  Not Available        56045

                                             funding_code  \
0       502 LOAN - GENERAL INTEREST SUBSIDY LOW & OTHE...
1       502 LOAN - GENERAL INTEREST SUBSIDY VERY LOW I...
2       SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...
3       SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...
4       SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...
...                                                   ...
420750  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...
420751  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...
420752  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...
420753  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...
420754  SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...

                 program_area investment_dollars  number_of_investments  year
0       Single Family Housing            130,000                      1  2015
1       Single Family Housing            169,800                      2  2015
2       Single Family Housing            147,959                      1  2015
3       Single Family Housing            962,764                      6  2015
4       Single Family Housing            121,428                      1  2015
...                       ...                ...                    ...   ...
420750  Single Family Housing            249,494                      1  2025
420751  Single Family Housing            257,575                      1  2025
420752  Single Family Housing            118,500                      1  2025
420753  Single Family Housing            202,020                      1  2025
420754  Single Family Housing            320,201                      2  2025

[138060 rows x 10 columns]

In [178]:
inv_df.head()

,fiscal_year,state,county,zip_code,county_fips,funding_code,program_area,investment_dollars,number_of_investments,year
0,2015,Alabama,Autauga,Not Available,1001,502 LOAN - GENERAL INTEREST SUBSIDY LOW & OTHE...,Single Family Housing,"130,000",1,2015
1,2015,Alabama,Autauga,Not Available,1001,502 LOAN - GENERAL INTEREST SUBSIDY VERY LOW I...,Single Family Housing,"169,800",2,2015
2,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"147,959",1,2015
3,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"962,764",6,2015
4,2015,Alabama,Autauga,Not Available,1001,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"121,428",1,2015
...,...,...,...,...,...,...,...,...,...,...
420750,2025,Wyoming,Washakie,Not Available,56043,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"249,494",1,2025
420751,2025,Wyoming,Washakie,Not Available,56043,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"257,575",1,2025
420752,2025,Wyoming,Washakie,Not Available,56043,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"118,500",1,2025
420753,2025,Wyoming,Weston,Not Available,56045,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"202,020",1,2025
420754,2025,Wyoming,Weston,Not Available,56045,SEC 502 GUARANTEED SINGLE FAMILY HOUSING PURCH...,Single Family Housing,"320,201",2,2025

In [179]:
# Drop the specified columns if they exist
cols_to_drop = ["funding_code", "program_area", "fiscal_year"]
inv_df = inv_df.obj if hasattr(inv_df, "obj") else inv_df
inv_df = inv_df.drop(columns=[c for c in cols_to_drop if c in inv_df.columns])

In [180]:
# Bring 'year' column to first position
cols = inv_df.columns.tolist()
if "year" in cols:
    cols.insert(0, cols.pop(cols.index("year")))
    inv_df = inv_df[cols]

In [181]:
inv_df.head()

,year,state,county,zip_code,county_fips,investment_dollars,number_of_investments
0,2015,Alabama,Autauga,Not Available,1001,"130,000",1
1,2015,Alabama,Autauga,Not Available,1001,"169,800",2
2,2015,Alabama,Autauga,Not Available,1001,"147,959",1
3,2015,Alabama,Autauga,Not Available,1001,"962,764",6
4,2015,Alabama,Autauga,Not Available,1001,"121,428",1

In [182]:
os.chdir(r"c:\Atharv\Git\fahe")
print(os.getcwd())

c:\Atharv\Git\fahe

In [183]:
# Load the list of Appalachian counties
keep_county = pd.read_csv(r"raw\appalachian_counties.csv")

In [184]:
# Standardize county_fips in inv_df
inv_df["county_fips"] = inv_df["county_fips"].astype(str).str.zfill(5)

In [185]:
# Standardize fips in keep_county
keep_county["county_fips"] = keep_county["fips"].astype(str).str.zfill(5)

In [186]:
# Merge on county_fips
inv_filtered = inv_df.merge(
    keep_county[["county_fips", "state", "county"]].drop_duplicates(),
    on="county_fips",
    how="inner"
)
print("Unique counties after join:", inv_filtered["county_fips"].nunique())

Unique counties after join: 423

In [187]:
inv_filtered.head()

,year,state_x,county_x,zip_code,county_fips,investment_dollars,number_of_investments,state_y,county_y
0,2015,Alabama,Bibb,Not Available,01007,"81,530",1,Alabama,Bibb
1,2015,Alabama,Bibb,Not Available,01007,"93,367",1,Alabama,Bibb
2,2015,Alabama,Bibb,Not Available,01007,"278,060",2,Alabama,Bibb
3,2015,Alabama,Bibb,Not Available,01007,"126,530",1,Alabama,Bibb
4,2015,Alabama,Bibb,Not Available,01007,"91,836",1,Alabama,Bibb

In [188]:
# Drop columns: state_y, county_y, zip_code
inv_filtered = inv_filtered.drop(columns=["state_y", "county_y", "zip_code"], errors="ignore")

# Rename columns: state_x -> state, county_x -> county
inv_filtered = inv_filtered.rename(columns={"state_x": "state", "county_x": "county"})

In [189]:
# Remove commas and convert investment_dollars to numeric
inv_filtered["investment_dollars"] = inv_filtered["investment_dollars"].replace({",": ""}, regex=True).astype(float)

# Aggregate per county and per year
df_investment = inv_filtered.groupby(["county_fips", "state", "county", "year"], as_index=False).agg({
    "investment_dollars": "sum",
    "number_of_investments": "sum"
})

# Rename columns for clarity
df_investment = df_investment.rename(columns={
    "investment_dollars": "total_investment_dollars",
    "number_of_investments": "total_number_of_investments"
})

print(df_investment.head())

  county_fips    state county  year  total_investment_dollars  \
0       01007  Alabama   Bibb  2015                 1273871.0
1       01007  Alabama   Bibb  2016                  658855.0
2       01007  Alabama   Bibb  2017                 1710111.0
3       01007  Alabama   Bibb  2018                 2219547.0
4       01007  Alabama   Bibb  2019                 1596396.0

   total_number_of_investments
0                           10
1                            7
2                           15
3                           16
4                           13

In [190]:
# Check missing values in all columns for df_investment
print("Missing values in df_investment:")
print(df_investment.isnull().sum())

Missing values in df_investment:
county_fips                    0
state                          0
county                         0
year                           0
total_investment_dollars       0
total_number_of_investments    0
dtype: int64

In [191]:
df_investment.head()

,county_fips,state,county,year,total_investment_dollars,total_number_of_investments
0,01007,Alabama,Bibb,2015,1273871.0,10
1,01007,Alabama,Bibb,2016,658855.0,7
2,01007,Alabama,Bibb,2017,1710111.0,15
3,01007,Alabama,Bibb,2018,2219547.0,16
4,01007,Alabama,Bibb,2019,1596396.0,13

# Income Limits

In [408]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [409]:
import glob

# Path to the directory containing all income limits CSV files
income_limits_dir = os.path.join("..", "raw", "Income_limits")
all_csv_files = glob.glob(os.path.join(income_limits_dir, "*.csv"))

dfs_income_limits = []
for file in all_csv_files:
    # Extract year from filename (e.g., 2015.csv → 2015)
    year = os.path.splitext(os.path.basename(file))[0]
    df = pd.read_csv(file)
    df["year"] = year  # Add year column
    dfs_income_limits.append(df)

# Combine all with year included
df_income_limits = pd.concat(dfs_income_limits, ignore_index=True)

print(f"Found {len(all_csv_files)} income limits CSV files:")
for file in all_csv_files:
    print(f" - {os.path.basename(file)}")

print(df_income_limits.head())

Found 9 income limits CSV files:
 - 2015.csv
 - 2016.csv
 - 2017.csv
 - 2018.csv
 - 2019.csv
 - 2020.csv
 - 2021.csv
 - 2022.csv
 - 2023.csv
   State statename           CBSASub  \
0    1.0   ALABAMA  METRO33860M33860
1    1.0   ALABAMA  NCNTY01003N01003
2    1.0   ALABAMA  NCNTY01005N01005
3    1.0   ALABAMA  METRO13820M13820
4    1.0   ALABAMA  METRO13820M13820

                                   Areaname   fips2010  Lim30_15p1  \
0                        Montgomery, AL MSA  100199999     12500.0
1                        Baldwin County, AL  100399999     12700.0
2                        Barbour County, AL  100599999     10200.0
3  Birmingham-Hoover, AL HUD Metro FMR Area  100799999     13150.0
4  Birmingham-Hoover, AL HUD Metro FMR Area  100999999     13150.0

   Lim30_15p2  Lim30_15p3  Lim30_15p4  Lim30_15p5  ...  Lim80_23p7  \
0     14250.0     16050.0     17800.0     19250.0  ...         NaN
1     14500.0     16300.0     18100.0     19550.0  ...         NaN
2     11650.0     13100.0     14550.0     15750.0  ...         NaN
3     15000.0     16900.0     18750.0     20250.0  ...         NaN
4     15000.0     16900.0     18750.0     20250.0  ...         NaN

   Lim80_23p8  lim120_23p1  lim120_23p2  lim120_23p3  lim120_23p4  \
0         NaN          NaN          NaN          NaN          NaN
1         NaN          NaN          NaN          NaN          NaN
2         NaN          NaN          NaN          NaN          NaN
3         NaN          NaN          NaN          NaN          NaN
4         NaN          NaN          NaN          NaN          NaN

   lim120_23p5  lim120_23p6  lim120_23p7  lim120_23p8
0          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN

[5 rows x 315 columns]

In [410]:
df_income_limits.head()

,State,statename,CBSASub,Areaname,fips2010,Lim30_15p1,Lim30_15p2,Lim30_15p3,Lim30_15p4,Lim30_15p5,...,Lim80_23p7,Lim80_23p8,lim120_23p1,lim120_23p2,lim120_23p3,lim120_23p4,lim120_23p5,lim120_23p6,lim120_23p7,lim120_23p8
0,1.0,ALABAMA,METRO33860M33860,"Montgomery, AL MSA",100199999,12500.0,14250.0,16050.0,17800.0,19250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,ALABAMA,NCNTY01003N01003,"Baldwin County, AL",100399999,12700.0,14500.0,16300.0,18100.0,19550.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,ALABAMA,NCNTY01005N01005,"Barbour County, AL",100599999,10200.0,11650.0,13100.0,14550.0,15750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,ALABAMA,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",100799999,13150.0,15000.0,16900.0,18750.0,20250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,ALABAMA,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",100999999,13150.0,15000.0,16900.0,18750.0,20250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [411]:
# Make all column names lower case and replace spaces with underscores
df_income_limits.columns = [col.lower().replace(" ", "_") for col in df_income_limits.columns]

In [412]:
# Remove specified columns if they exist
cols_to_remove = ["cbsasub", "hud_area_name", "county_town_name", "state", "county", "areaname"]
df_income_limits = df_income_limits.drop(columns=[col for col in cols_to_remove if col in df_income_limits.columns], errors="ignore")

In [413]:
# Rename columns as specified
rename_map = {
    "statename": "state",
    "fips2010": "county_fips",
    "county_name": "county"
}
df_income_limits = df_income_limits.rename(columns=rename_map)

In [414]:
df_income_limits.head()

,state,county_fips,lim30_15p1,lim30_15p2,lim30_15p3,lim30_15p4,lim30_15p5,lim30_15p6,lim30_15p7,lim30_15p8,...,lim80_23p7,lim80_23p8,lim120_23p1,lim120_23p2,lim120_23p3,lim120_23p4,lim120_23p5,lim120_23p6,lim120_23p7,lim120_23p8
0,ALABAMA,100199999,12500.0,14250.0,16050.0,17800.0,19250.0,20650.0,22100.0,23500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,100399999,12700.0,14500.0,16300.0,18100.0,19550.0,21000.0,22450.0,23900.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ALABAMA,100599999,10200.0,11650.0,13100.0,14550.0,15750.0,16900.0,18050.0,19250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALABAMA,100799999,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,23250.0,24750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALABAMA,100999999,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,23250.0,24750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [415]:
# Convert 'state' column to title case if it exists
if "state" in df_income_limits.columns:
    df_income_limits["state"] = df_income_limits["state"].astype(str).str.title()

In [416]:
# Ensure county_fips is a string and pad to 10 digits with leading zeros
df_income_limits["county_fips"] = df_income_limits["county_fips"].astype(str).str.zfill(10)

In [418]:
# Keep only the first 5 digits of county_fips
df_income_limits["county_fips"] = df_income_limits["county_fips"].astype(str).str[:5]

In [363]:

# Ensure county_fips is a 5-character string, padded with leading zeros
df_income_limits["county_fips"] = df_income_limits["county_fips"].astype(str).str.zfill(5)

In [420]:
# Rename columns according to the specified mapping
income_limit_rename_map = {
    "lim30": "extreme_low_income_<=30%",
    "lim50": "very_low_income_<=50%",
    "lim60": "low_income_<=60%",
    "lim80": "low_income_<=80%",
    "lim120": "moderate_income_<=120%"
}

# For each column, if it starts with one of the keys, rename accordingly
new_columns = {}
for col in df_income_limits.columns:
    for old_prefix, new_prefix in income_limit_rename_map.items():
        if col.startswith(old_prefix + "_"):
            suffix = col[len(old_prefix):]  # e.g., _25p1
            new_col = new_prefix + suffix
            new_columns[col] = new_col
            break  # Only match one prefix per column

df_income_limits = df_income_limits.rename(columns=new_columns)

In [421]:
df_income_limits.head()

,state,county_fips,extreme_low_income_<=30%_15p1,extreme_low_income_<=30%_15p2,extreme_low_income_<=30%_15p3,extreme_low_income_<=30%_15p4,extreme_low_income_<=30%_15p5,extreme_low_income_<=30%_15p6,extreme_low_income_<=30%_15p7,extreme_low_income_<=30%_15p8,...,low_income_<=80%_23p7,low_income_<=80%_23p8,moderate_income_<=120%_23p1,moderate_income_<=120%_23p2,moderate_income_<=120%_23p3,moderate_income_<=120%_23p4,moderate_income_<=120%_23p5,moderate_income_<=120%_23p6,moderate_income_<=120%_23p7,moderate_income_<=120%_23p8
0,Alabama,01001,12500.0,14250.0,16050.0,17800.0,19250.0,20650.0,22100.0,23500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alabama,01003,12700.0,14500.0,16300.0,18100.0,19550.0,21000.0,22450.0,23900.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alabama,01005,10200.0,11650.0,13100.0,14550.0,15750.0,16900.0,18050.0,19250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alabama,01007,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,23250.0,24750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alabama,01009,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,23250.0,24750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [422]:
# Keep only rows where 'state' is in the specified list of states
states_to_keep = [
    "Alabama", "Georgia", "Kentucky", "Maryland", "Mississippi", "New York",
    "North Carolina", "Ohio", "Pennsylvania", "South Carolina", "Tennessee",
    "Virginia", "West Virginia"
]
df_income_limits = df_income_limits[df_income_limits["state"].isin(states_to_keep)].reset_index(drop=True)

In [423]:
os.chdir(r"c:\Atharv\Git\fahe\filtered")
print(os.getcwd())

c:\Atharv\Git\fahe\filtered

In [424]:
df_income_limits.to_csv("filtered_income_limits.csv", index=False)

In [425]:
# Replace all occurrences of '(X)' with None (null in pandas)
df_income_limits = df_income_limits.replace('(X)', None)

In [429]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [430]:
# Load the list of Appalachian counties
keep_county = pd.read_csv("appalachian_counties.csv")

In [431]:
# Standardize county_fips 
df_income_limits["county_fips"] = df_income_limits["county_fips"].astype(str).str.zfill(5)

In [432]:
# Standardize fips in keep_county
keep_county["county_fips"] = keep_county["fips"].astype(str).str.zfill(5)

In [433]:
# Filter df_income_limits to only include the 423 counties present in keep_county
appalachian_fips = keep_county["county_fips"].unique()
df_income_limits = df_income_limits[df_income_limits["county_fips"].isin(appalachian_fips)].copy()
print("Number of unique counties in df_income_limits after filtering:", df_income_limits["county_fips"].nunique())

Number of unique counties in df_income_limits after filtering: 423

In [435]:
df_income_limits.head()

,state,county_fips,extreme_low_income_<=30%_15p1,extreme_low_income_<=30%_15p2,extreme_low_income_<=30%_15p3,extreme_low_income_<=30%_15p4,extreme_low_income_<=30%_15p5,extreme_low_income_<=30%_15p6,extreme_low_income_<=30%_15p7,extreme_low_income_<=30%_15p8,...,low_income_<=80%_23p7,low_income_<=80%_23p8,moderate_income_<=120%_23p1,moderate_income_<=120%_23p2,moderate_income_<=120%_23p3,moderate_income_<=120%_23p4,moderate_income_<=120%_23p5,moderate_income_<=120%_23p6,moderate_income_<=120%_23p7,moderate_income_<=120%_23p8
3,Alabama,01007,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,23250.0,24750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alabama,01009,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,23250.0,24750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alabama,01015,10400.0,11850.0,13350.0,14800.0,16000.0,17200.0,18400.0,19550.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,01017,10200.0,11650.0,13100.0,14550.0,15750.0,16900.0,18050.0,19250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Alabama,01019,10500.0,12000.0,13500.0,14950.0,16150.0,17350.0,18550.0,19750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [436]:
# Add county name to df_income_limits by mapping from keep_county using county_fips
county_fips_to_name = dict(zip(keep_county["county_fips"], keep_county["county"]))
df_income_limits["county"] = df_income_limits["county_fips"].map(county_fips_to_name)

In [438]:
# Rearrange columns: year, county_fips, county, state, then the rest
cols = df_income_limits.columns.tolist()
main_cols = ['year', 'county_fips', 'county', 'state']
rest_cols = [col for col in cols if col not in main_cols]
df_income_limits = df_income_limits[main_cols + rest_cols]

In [439]:
df_income_limits.head()

,year,county_fips,county,state,extreme_low_income_<=30%_15p1,extreme_low_income_<=30%_15p2,extreme_low_income_<=30%_15p3,extreme_low_income_<=30%_15p4,extreme_low_income_<=30%_15p5,extreme_low_income_<=30%_15p6,...,low_income_<=80%_23p7,low_income_<=80%_23p8,moderate_income_<=120%_23p1,moderate_income_<=120%_23p2,moderate_income_<=120%_23p3,moderate_income_<=120%_23p4,moderate_income_<=120%_23p5,moderate_income_<=120%_23p6,moderate_income_<=120%_23p7,moderate_income_<=120%_23p8
3,2015,01007,Bibb,Alabama,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,01009,Blount,Alabama,13150.0,15000.0,16900.0,18750.0,20250.0,21750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,01015,Calhoun,Alabama,10400.0,11850.0,13350.0,14800.0,16000.0,17200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,01017,Chambers,Alabama,10200.0,11650.0,13100.0,14550.0,15750.0,16900.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,01019,Cherokee,Alabama,10500.0,12000.0,13500.0,14950.0,16150.0,17350.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Median Home Price

In [588]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [589]:
df_home_prices = pd.read_csv("Median Home Price/median_house_price.csv")

In [590]:
df_home_prices.head()

,County Name,Median Home Price Q1 2025,Monthly Payment Q1 2025,Monthly Payment Q1 2024
0,"Nantucket County, Massachusetts","$1,700,990","$10,010","$9,330"
1,"Marin County, California","$1,630,020","$9,590","$9,570"
2,"San Mateo County, California","$1,608,890","$9,470","$9,450"
3,"Santa Clara County, California","$1,588,730","$9,350","$9,190"
4,"Teton County, Wyoming","$1,535,580","$9,040","$8,440"

In [591]:
# Clean up column names: lower case, replace spaces and underscores with single underscore, and rename specific columns
df_home_prices = df_home_prices.rename(columns=lambda x: x.strip().lower().replace(" ", "_").replace("__", "_").replace("\n", "_").replace("__", "_"))
df_home_prices = df_home_prices.rename(columns={
    "county_name": "county",
    "median_home_price_q1_2025": "median_home_price_2025",
    "monthly_payment_q1_2025": "monthly_payment_2025"
})
# Remove the column 'monthly_payment_q1_2024' if it exists
if "monthly_payment_q1_2024" in df_home_prices.columns:
    df_home_prices = df_home_prices.drop(columns=["monthly_payment_q1_2024"])

In [592]:
# Print the length of unique counties in df_home_prices
print(len(df_home_prices['county'].unique()))

3105

In [593]:
# Remove '$' and commas from price columns and convert to numeric
for col in ['median_home_price_2025', 'monthly_payment_2025']:
    if col in df_home_prices.columns:
        df_home_prices[col] = (
            df_home_prices[col]
            .astype(str)
            .str.replace('$', '', regex=False)
            .str.replace(',', '', regex=False)
            .str.strip()
        )
        # Convert to int (no float), coerce errors to NaN
        df_home_prices[col] = pd.to_numeric(df_home_prices[col], errors='coerce').astype('Int64')

In [594]:
df_home_prices.head()

,county,median_home_price_2025,monthly_payment_2025
0,"Nantucket County, Massachusetts",1700990,10010
1,"Marin County, California",1630020,9590
2,"San Mateo County, California",1608890,9470
3,"Santa Clara County, California",1588730,9350
4,"Teton County, Wyoming",1535580,9040

In [595]:
# Only keep counties whose names end with the specified state names
state_suffixes = [
    "Alabama", "Georgia", "Kentucky", "Maryland", "Mississippi", "New York",
    "North Carolina", "Ohio", "Pennsylvania", "South Carolina", "Tennessee",
    "Virginia", "West Virginia"
]
# Build regex pattern for matching county names ending with these states
pattern = r"(" + "|".join([rf"{state}$" for state in state_suffixes]) + r")"
df_home_prices = df_home_prices[df_home_prices['county'].str.strip().str.endswith(tuple(state_suffixes))]

In [596]:
df_home_prices.head()

                          county  median_home_price_2025  monthly_payment_2025
8      New York County, New York                 1174240                  6910
12   Falls Church city, Virginia                 1061170                  6250
15        Kings County, New York                 1022630                  6020
25    Arlington County, Virginia                  898100                  5290
33  Williamson County, Tennessee                  837520                  4930

In [597]:
# Extract state name from county and create a new 'state' column
state_names = [
    "Alabama", "Georgia", "Kentucky", "Maryland", "Mississippi", "New York",
    "North Carolina", "Ohio", "Pennsylvania", "South Carolina", "Tennessee",
    "Virginia", "West Virginia"
]
# Build regex pattern to match state at end of string
state_pattern = r"(" + "|".join([re.escape(state) for state in state_names]) + r")$"
df_home_prices['state'] = df_home_prices['county'].str.extract(state_pattern, expand=False)

In [598]:
# Remove state names, "county", and commas from the 'county' column
remove_words = [
    "Alabama", "Georgia", "Kentucky", "Maryland", "Mississippi", "New York",
    "North Carolina", "Ohio", "Pennsylvania", "South Carolina", "Tennessee",
    "Virginia", "West Virginia", "County"
]
# Build regex pattern to match any of the words (case-insensitive), and also commas
pattern = r"\b(" + "|".join([re.escape(word) for word in remove_words]) + r")\b|,"

df_home_prices['county'] = (
    df_home_prices['county']
    .str.replace(pattern, '', regex=True, case=False)
    .str.strip()
    .replace(r'\s+', ' ', regex=True)
)

In [599]:
if 'county_lastword' in df_home_prices.columns:
    df_home_prices = df_home_prices.drop(columns=['county_lastword'])

In [600]:
# Rearrange columns: county, state, and the rest
cols = ['county', 'state'] + [col for col in df_home_prices.columns if col not in ['county', 'state']]
df_home_prices = df_home_prices[cols]

In [601]:
df_home_prices = df_home_prices.sort_values(by='state', ascending=True).reset_index(drop=True)

In [602]:
df_home_prices.head()

       county    state  median_home_price_2025  monthly_payment_2025
0       Henry  Alabama                  158640                   930
1     Russell  Alabama                  167870                   990
2     Lowndes  Alabama                   91300                   540
3  Montgomery  Alabama                  193360                  1140
4   Limestone  Alabama                  314830                  1850

In [603]:
os.chdir(r"c:\Atharv\Git\fahe\raw")
print(os.getcwd())

c:\Atharv\Git\fahe\raw

In [604]:
# Load the list of Appalachian counties
keep_county = pd.read_csv("appalachian_counties.csv")

In [605]:
# Standardize fips in keep_county
keep_county["county_fips"] = keep_county["fips"].astype(str).str.zfill(5)

In [606]:
keep_county.head()

   fips    state    county county_fips
0  1007  Alabama      Bibb       01007
1  1009  Alabama    Blount       01009
2  1015  Alabama   Calhoun       01015
3  1017  Alabama  Chambers       01017
4  1019  Alabama  Cherokee       01019

In [607]:
# Merge keep_county with df_home_prices to match only Appalachian counties
df_home_prices = df_home_prices.merge(
    keep_county[['county', 'state', 'county_fips']],
    how='inner',
    left_on=['county', 'state'],
    right_on=['county', 'state']
)

In [ ]:
df_home_prices = df_home_prices.sort_values(by='county_fips', ascending=True).reset_index(drop=True)
df_home_prices.head()

In [612]:
# Check if df_home_prices contains all 423 Appalachian counties
num_appalachian_counties = keep_county['county_fips'].nunique()
num_in_home_prices = df_home_prices['county_fips'].nunique()
print(f"Number of Appalachian counties in keep_county: {num_appalachian_counties}")
print(f"Number of counties in df_home_prices: {num_in_home_prices}")
if num_in_home_prices == num_appalachian_counties:
    print("df_home_prices contains all 423 Appalachian counties.")
else:
    print(f"df_home_prices is missing {num_appalachian_counties - num_in_home_prices} counties.")
    missing = set(keep_county['county_fips']) - set(df_home_prices['county_fips'])
    if missing:
        print("Missing county_fips:", sorted(missing))

Number of Appalachian counties in keep_county: 423
Number of counties in df_home_prices: 411
df_home_prices is missing 12 counties.
Missing county_fips: ['01049', '24001', '47041', '51005', '51035', '51089', '51121', '51163', '51191', '51195', '54057', '54069']

In [613]:
# Add missing values for specific county_fips in df_home_prices
missing_home_prices = [
    {"county_fips": "01049", "median_home_price_2025": 296590, "monthly_payment_2025": 1750},
    {"county_fips": "24001", "median_home_price_2025": 505750, "monthly_payment_2025": 2980},
    {"county_fips": "47041", "median_home_price_2025": 140840, "monthly_payment_2025": 830},
    {"county_fips": "51005", "median_home_price_2025": 781120, "monthly_payment_2025": 4600},
    {"county_fips": "51035", "median_home_price_2025": 385710, "monthly_payment_2025": 2270},
    {"county_fips": "51089", "median_home_price_2025": 230160, "monthly_payment_2025": 1350},
    {"county_fips": "51121", "median_home_price_2025": 170710, "monthly_payment_2025": 1000},
    {"county_fips": "51163", "median_home_price_2025": 139430, "monthly_payment_2025": 820},
    {"county_fips": "51191", "median_home_price_2025": 101210, "monthly_payment_2025": 600},
    {"county_fips": "51195", "median_home_price_2025": 86800,  "monthly_payment_2025": 510},
    {"county_fips": "54069", "median_home_price_2025": 162440, "monthly_payment_2025": 960},
]

for entry in missing_home_prices:
    # Get county and state from keep_county for this county_fips
    row = keep_county[keep_county["county_fips"] == entry["county_fips"]]
    if not row.empty:
        county = row.iloc[0]["county"]
        state = row.iloc[0]["state"]
        # Only add if not already present in df_home_prices
        if not ((df_home_prices["county_fips"] == entry["county_fips"]).any()):
            df_home_prices = pd.concat([
                df_home_prices,
                pd.DataFrame([{
                    "county": county,
                    "state": state,
                    "county_fips": entry["county_fips"],
                    "median_home_price_2025": entry["median_home_price_2025"],
                    "monthly_payment_2025": entry["monthly_payment_2025"]
                }])
            ], ignore_index=True)

In [615]:
df_home_prices.head()

     county    state  median_home_price_2025  monthly_payment_2025 county_fips
0      Bibb  Alabama                  143650                   850       01007
1    Blount  Alabama                  183840                  1080       01009
2   Calhoun  Alabama                  168460                   990       01015
3  Chambers  Alabama                  145280                   850       01017
4  Cherokee  Alabama                  185820                  1090       01019

In [616]:
os.chdir(r"c:\Atharv\Git\fahe\filtered")
print(os.getcwd())

c:\Atharv\Git\fahe\filtered

In [617]:
df_home_prices.to_csv("filtered_home_prices.csv", index=False)

# Combining these all together

In [634]:
print("df_poverty columns:", df_poverty.columns.tolist())
print("df_investment columns:", df_investment.columns.tolist())
print("df_income columns:", df_income.columns.tolist())
print("df_education columns:", df_education.columns.tolist())
print("df_home_prices columns:", df_home_prices.columns.tolist())
print("df_income_limits columns:", df_income_limits.columns.tolist())

df_poverty columns: ['geo_id', 'state', 'county', 'year', 'total_population', 'population_below_poverty', 'population_below_poverty_percent', 'adults_25_and_older_less_than_high_school_graduate', 'adults_25_and_older_less_than_high_school_graduate_percent', "adults_25_and_older_with_bachelor's_degree_or_higher", "adults_25_and_older_with_bachelor's_degree_or_higher_percent", 'county_fips']
df_investment columns: ['county_fips', 'state', 'county', 'year', 'total_investment_dollars', 'total_number_of_investments']
df_income columns: ['geo_id', 'state', 'county', 'year', 'number_of_households', 'average_income_per_household', 'county_fips']
df_education columns: ['geo_id', 'state', 'county', 'year', 'total_median_earnings', 'county_fips']
df_home_prices columns: ['county', 'state', 'median_home_price_2025', 'monthly_payment_2025', 'county_fips']
df_income_limits columns: ['year', 'county_fips', 'county', 'state', 'extreme_low_income_<=30%_15p1', 'extreme_low_income_<=30%_15p2', 'extreme_low_income_<=30%_15p3', 'extreme_low_income_<=30%_15p4', 'extreme_low_income_<=30%_15p5', 'extreme_low_income_<=30%_15p6', 'extreme_low_income_<=30%_15p7', 'extreme_low_income_<=30%_15p8', 'very_low_income_<=50%_15p1', 'very_low_income_<=50%_15p2', 'very_low_income_<=50%_15p3', 'very_low_income_<=50%_15p4', 'very_low_income_<=50%_15p5', 'very_low_income_<=50%_15p6', 'very_low_income_<=50%_15p7', 'very_low_income_<=50%_15p8', 'low_income_<=60%_15p1', 'low_income_<=60%_15p2', 'low_income_<=60%_15p3', 'low_income_<=60%_15p4', 'low_income_<=60%_15p5', 'low_income_<=60%_15p6', 'low_income_<=60%_15p7', 'low_income_<=60%_15p8', 'low_income_<=80%_15p1', 'low_income_<=80%_15p2', 'low_income_<=80%_15p3', 'low_income_<=80%_15p4', 'low_income_<=80%_15p5', 'low_income_<=80%_15p6', 'low_income_<=80%_15p7', 'low_income_<=80%_15p8', 'extreme_low_income_<=30%_16p1', 'extreme_low_income_<=30%_16p2', 'extreme_low_income_<=30%_16p3', 'extreme_low_income_<=30%_16p4', 'extreme_low_income_<=30%_16p5', 'extreme_low_income_<=30%_16p6', 'extreme_low_income_<=30%_16p7', 'extreme_low_income_<=30%_16p8', 'very_low_income_<=50%_16p1', 'very_low_income_<=50%_16p2', 'very_low_income_<=50%_16p3', 'very_low_income_<=50%_16p4', 'very_low_income_<=50%_16p5', 'very_low_income_<=50%_16p6', 'very_low_income_<=50%_16p7', 'very_low_income_<=50%_16p8', 'low_income_<=60%_16p1', 'low_income_<=60%_16p2', 'low_income_<=60%_16p3', 'low_income_<=60%_16p4', 'low_income_<=60%_16p5', 'low_income_<=60%_16p6', 'low_income_<=60%_16p7', 'low_income_<=60%_16p8', 'low_income_<=80%_16p1', 'low_income_<=80%_16p2', 'low_income_<=80%_16p3', 'low_income_<=80%_16p4', 'low_income_<=80%_16p5', 'low_income_<=80%_16p6', 'low_income_<=80%_16p7', 'low_income_<=80%_16p8', 'extreme_low_income_<=30%_17p1', 'extreme_low_income_<=30%_17p2', 'extreme_low_income_<=30%_17p3', 'extreme_low_income_<=30%_17p4', 'extreme_low_income_<=30%_17p5', 'extreme_low_income_<=30%_17p6', 'extreme_low_income_<=30%_17p7', 'extreme_low_income_<=30%_17p8', 'very_low_income_<=50%_17p1', 'very_low_income_<=50%_17p2', 'very_low_income_<=50%_17p3', 'very_low_income_<=50%_17p4', 'very_low_income_<=50%_17p5', 'very_low_income_<=50%_17p6', 'very_low_income_<=50%_17p7', 'very_low_income_<=50%_17p8', 'low_income_<=60%_17p1', 'low_income_<=60%_17p2', 'low_income_<=60%_17p3', 'low_income_<=60%_17p4', 'low_income_<=60%_17p5', 'low_income_<=60%_17p6', 'low_income_<=60%_17p7', 'low_income_<=60%_17p8', 'low_income_<=80%_17p1', 'low_income_<=80%_17p2', 'low_income_<=80%_17p3', 'low_income_<=80%_17p4', 'low_income_<=80%_17p5', 'low_income_<=80%_17p6', 'low_income_<=80%_17p7', 'low_income_<=80%_17p8', 'extreme_low_income_<=30%_18p1', 'extreme_low_income_<=30%_18p2', 'extreme_low_income_<=30%_18p3', 'extreme_low_income_<=30%_18p4', 'extreme_low_income_<=30%_18p5', 'extreme_low_income_<=30%_18p6', 'extreme_low_income_<=30%_18p7', 'extreme_low_income_<=30%_18p8', 'very_low_income_<=50%_18p1', 'very_low_income_<=50%_18p2', 'very_low_income_<=50%_18p3', 'very_low_income_<=50%_18p4', 'very_low_income_<=50%_18p5', 'very_low_income_<=50%_18p6', 'very_low_income_<=50%_18p7', 'very_low_income_<=50%_18p8', 'low_income_<=60%_18p1', 'low_income_<=60%_18p2', 'low_income_<=60%_18p3', 'low_income_<=60%_18p4', 'low_income_<=60%_18p5', 'low_income_<=60%_18p6', 'low_income_<=60%_18p7', 'low_income_<=60%_18p8', 'low_income_<=80%_18p1', 'low_income_<=80%_18p2', 'low_income_<=80%_18p3', 'low_income_<=80%_18p4', 'low_income_<=80%_18p5', 'low_income_<=80%_18p6', 'low_income_<=80%_18p7', 'low_income_<=80%_18p8', 'extreme_low_income_<=30%_19p1', 'extreme_low_income_<=30%_19p2', 'extreme_low_income_<=30%_19p3', 'extreme_low_income_<=30%_19p4', 'extreme_low_income_<=30%_19p5', 'extreme_low_income_<=30%_19p6', 'extreme_low_income_<=30%_19p7', 'extreme_low_income_<=30%_19p8', 'very_low_income_<=50%_19p1', 'very_low_income_<=50%_19p2', 'very_low_income_<=50%_19p3', 'very_low_income_<=50%_19p4', 'very_low_income_<=50%_19p5', 'very_low_income_<=50%_19p6', 'very_low_income_<=50%_19p7', 'very_low_income_<=50%_19p8', 'low_income_<=60%_19p1', 'low_income_<=60%_19p2', 'low_income_<=60%_19p3', 'low_income_<=60%_19p4', 'low_income_<=60%_19p5', 'low_income_<=60%_19p6', 'low_income_<=60%_19p7', 'low_income_<=60%_19p8', 'low_income_<=80%_19p1', 'low_income_<=80%_19p2', 'low_income_<=80%_19p3', 'low_income_<=80%_19p4', 'low_income_<=80%_19p5', 'low_income_<=80%_19p6', 'low_income_<=80%_19p7', 'low_income_<=80%_19p8', 'extreme_low_income_<=30%_20p1', 'extreme_low_income_<=30%_20p2', 'extreme_low_income_<=30%_20p3', 'extreme_low_income_<=30%_20p4', 'extreme_low_income_<=30%_20p5', 'extreme_low_income_<=30%_20p6', 'extreme_low_income_<=30%_20p7', 'extreme_low_income_<=30%_20p8', 'very_low_income_<=50%_20p1', 'very_low_income_<=50%_20p2', 'very_low_income_<=50%_20p3', 'very_low_income_<=50%_20p4', 'very_low_income_<=50%_20p5', 'very_low_income_<=50%_20p6', 'very_low_income_<=50%_20p7', 'very_low_income_<=50%_20p8', 'low_income_<=60%_20p1', 'low_income_<=60%_20p2', 'low_income_<=60%_20p3', 'low_income_<=60%_20p4', 'low_income_<=60%_20p5', 'low_income_<=60%_20p6', 'low_income_<=60%_20p7', 'low_income_<=60%_20p8', 'low_income_<=80%_20p1', 'low_income_<=80%_20p2', 'low_income_<=80%_20p3', 'low_income_<=80%_20p4', 'low_income_<=80%_20p5', 'low_income_<=80%_20p6', 'low_income_<=80%_20p7', 'low_income_<=80%_20p8', 'extreme_low_income_<=30%_21p1', 'extreme_low_income_<=30%_21p2', 'extreme_low_income_<=30%_21p3', 'extreme_low_income_<=30%_21p4', 'extreme_low_income_<=30%_21p5', 'extreme_low_income_<=30%_21p6', 'extreme_low_income_<=30%_21p7', 'extreme_low_income_<=30%_21p8', 'very_low_income_<=50%_21p1', 'very_low_income_<=50%_21p2', 'very_low_income_<=50%_21p3', 'very_low_income_<=50%_21p4', 'very_low_income_<=50%_21p5', 'very_low_income_<=50%_21p6', 'very_low_income_<=50%_21p7', 'very_low_income_<=50%_21p8', 'low_income_<=60%_21p1', 'low_income_<=60%_21p2', 'low_income_<=60%_21p3', 'low_income_<=60%_21p4', 'low_income_<=60%_21p5', 'low_income_<=60%_21p6', 'low_income_<=60%_21p7', 'low_income_<=60%_21p8', 'low_income_<=80%_21p1', 'low_income_<=80%_21p2', 'low_income_<=80%_21p3', 'low_income_<=80%_21p4', 'low_income_<=80%_21p5', 'low_income_<=80%_21p6', 'low_income_<=80%_21p7', 'low_income_<=80%_21p8', 'extreme_low_income_<=30%_22p1', 'extreme_low_income_<=30%_22p2', 'extreme_low_income_<=30%_22p3', 'extreme_low_income_<=30%_22p4', 'extreme_low_income_<=30%_22p5', 'extreme_low_income_<=30%_22p6', 'extreme_low_income_<=30%_22p7', 'extreme_low_income_<=30%_22p8', 'very_low_income_<=50%_22p1', 'very_low_income_<=50%_22p2', 'very_low_income_<=50%_22p3', 'very_low_income_<=50%_22p4', 'very_low_income_<=50%_22p5', 'very_low_income_<=50%_22p6', 'very_low_income_<=50%_22p7', 'very_low_income_<=50%_22p8', 'low_income_<=60%_22p1', 'low_income_<=60%_22p2', 'low_income_<=60%_22p3', 'low_income_<=60%_22p4', 'low_income_<=60%_22p5', 'low_income_<=60%_22p6', 'low_income_<=60%_22p7', 'low_income_<=60%_22p8', 'low_income_<=80%_22p1', 'low_income_<=80%_22p2', 'low_income_<=80%_22p3', 'low_income_<=80%_22p4', 'low_income_<=80%_22p5', 'low_income_<=80%_22p6', 'low_income_<=80%_22p7', 'low_income_<=80%_22p8', 'moderate_income_<=120%_22p1', 'moderate_income_<=120%_22p2', 'moderate_income_<=120%_22p3', 'moderate_income_<=120%_22p4', 'moderate_income_<=120%_22p5', 'moderate_income_<=120%_22p6', 'moderate_income_<=120%_22p7', 'moderate_income_<=120%_22p8', 'extreme_low_income_<=30%_23p1', 'extreme_low_income_<=30%_23p2', 'extreme_low_income_<=30%_23p3', 'extreme_low_income_<=30%_23p4', 'extreme_low_income_<=30%_23p5', 'extreme_low_income_<=30%_23p6', 'extreme_low_income_<=30%_23p7', 'extreme_low_income_<=30%_23p8', 'very_low_income_<=50%_23p1', 'very_low_income_<=50%_23p2', 'very_low_income_<=50%_23p3', 'very_low_income_<=50%_23p4', 'very_low_income_<=50%_23p5', 'very_low_income_<=50%_23p6', 'very_low_income_<=50%_23p7', 'very_low_income_<=50%_23p8', 'low_income_<=60%_23p1', 'low_income_<=60%_23p2', 'low_income_<=60%_23p3', 'low_income_<=60%_23p4', 'low_income_<=60%_23p5', 'low_income_<=60%_23p6', 'low_income_<=60%_23p7', 'low_income_<=60%_23p8', 'low_income_<=80%_23p1', 'low_income_<=80%_23p2', 'low_income_<=80%_23p3', 'low_income_<=80%_23p4', 'low_income_<=80%_23p5', 'low_income_<=80%_23p6', 'low_income_<=80%_23p7', 'low_income_<=80%_23p8', 'moderate_income_<=120%_23p1', 'moderate_income_<=120%_23p2', 'moderate_income_<=120%_23p3', 'moderate_income_<=120%_23p4', 'moderate_income_<=120%_23p5', 'moderate_income_<=120%_23p6', 'moderate_income_<=120%_23p7', 'moderate_income_<=120%_23p8']

In [636]:
# Merge df_home_prices and df_income_limits on 'county_fips'
df_home_prices_income_limits = pd.merge(
    df_home_prices,
    df_income_limits,
    on="county_fips",
    how="outer",
    suffixes=('_home', '_limits')
)

In [294]:
KEYS = ["county_fips", "year"]

In [295]:
def clean(df):
    df = df.copy()
    df["county_fips"] = df["county_fips"].astype(str).str.zfill(5).str.strip()
    df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
    # drop rows with missing merge keys
    df = df.dropna(subset=KEYS)
    # keep the first record per (county_fips, year), no aggregation
    df = df.sort_values(KEYS).drop_duplicates(subset=KEYS, keep="first")
    return df

df_investment = clean(df_investment)
df_poverty    = clean(df_poverty)
df_income     = clean(df_income)
df_education  = clean(df_education)


# Change datatypes of specified columns to int for every df
for df in [df_education, df_income, df_poverty, df_investment]:
    for col in [
        "county_fips",
        "total_investment_dollars",
        "total_number_of_investments",
        "total_population",
        "population_below_poverty",
        "adults_25_and_older_less_than_high_school_graduate",
        "adults_25_and_older_with_bachelor's_degree_or_higher",
        "number_of_households",
        "average_income_per_household",
        "total_median_earnings"
    ]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
    # Change population_below_poverty_percent to float 
    if "population_below_poverty_percent" in df.columns:
        df["population_below_poverty_percent"] = pd.to_numeric(df["population_below_poverty_percent"], errors="coerce").astype(float)

In [296]:
base = (df_investment[["county_fips","state","county","year"]]
        .drop_duplicates(subset=KEYS))

final = (
    base
    .merge(df_investment[KEYS + ["total_investment_dollars","total_number_of_investments"]],
           on=KEYS, how="left", validate="one_to_one")  # Changed to "left"
    .merge(df_poverty[KEYS + ["total_population","population_below_poverty","population_below_poverty_percent",
                              "adults_25_and_older_less_than_high_school_graduate", "adults_25_and_older_less_than_high_school_graduate_percent",
                              "adults_25_and_older_with_bachelor's_degree_or_higher", "adults_25_and_older_with_bachelor's_degree_or_higher_percent"]],
           on=KEYS, how="left", validate="one_to_one")  # Changed to "left"
    .merge(df_income[KEYS + ["number_of_households","average_income_per_household"]],
           on=KEYS, how="left", validate="one_to_one")  # Changed to "left"
    .merge(df_education[KEYS + ["total_median_earnings"]],
           on=KEYS, how="left", validate="one_to_one")  # Changed to "left"
)

In [297]:
# 2a) remove rows with missing year (the “extra” in-between rows)
final = final[final["year"].notna()].copy()
final["year"] = final["year"].astype("Int64")

In [298]:
final_data = final.sort_values(["county_fips","year"]).reset_index(drop=True)

In [299]:
[k for k in ["county_fips","state","county","year"] if list(final_data.columns).count(k) > 1]
#to check if there are any duplicate keys

[]

In [300]:
final_data.dtypes

county_fips                                                       Int64
state                                                            object
county                                                           object
year                                                              Int64
total_investment_dollars                                          Int64
total_number_of_investments                                       Int64
total_population                                                  Int64
population_below_poverty                                          Int64
population_below_poverty_percent                                float64
adults_25_and_older_less_than_high_school_graduate                Int64
adults_25_and_older_less_than_high_school_graduate_percent      float64
adults_25_and_older_with_bachelor's_degree_or_higher              Int64
adults_25_and_older_with_bachelor's_degree_or_higher_percent    float64
number_of_households                                              Int64
average_income_per_household                                      Int64
total_median_earnings                                             Int64
dtype: object

In [301]:
# Check for missing/null values in each column of final_data
print("Missing/null values in each column of final_data:")
print(final_data.isnull().sum())

Missing/null values in each column of final_data:
county_fips                                                       0
state                                                             0
county                                                            0
year                                                              0
total_investment_dollars                                          0
total_number_of_investments                                       0
total_population                                                809
population_below_poverty                                        809
population_below_poverty_percent                                809
adults_25_and_older_less_than_high_school_graduate              809
adults_25_and_older_less_than_high_school_graduate_percent      809
adults_25_and_older_with_bachelor's_degree_or_higher            809
adults_25_and_older_with_bachelor's_degree_or_higher_percent    809
number_of_households                                            809
average_income_per_household                                    809
total_median_earnings                                           875
dtype: int64

In [282]:
final_data.head()

,county_fips,state,county,year,total_investment_dollars,total_number_of_investments,total_population,population_below_poverty,population_below_poverty_percent,adults_25_and_older_less_than_high_school_graduate,adults_25_and_older_less_than_high_school_graduate_percent,adults_25_and_older_with_bachelor's_degree_or_higher,adults_25_and_older_with_bachelor's_degree_or_higher_percent,number_of_households,average_income_per_household,total_median_earnings
0,1007,Alabama,Bibb,2015,1273871,10,20767,3488,16.8,2381,11.5,1657,8.0,7027,38678,29113
1,1007,Alabama,Bibb,2016,658855,7,20603,3390,16.5,2408,11.7,1878,9.1,7048,39776,30328
2,1007,Alabama,Bibb,2017,1710111,15,20555,3133,15.2,2170,10.6,2061,10.0,6916,43404,31833
3,1007,Alabama,Bibb,2018,2219547,16,20468,2863,14.0,1994,9.7,1784,8.7,6840,45340,32108
4,1007,Alabama,Bibb,2019,1596396,13,20632,3740,18.1,2714,13.2,1649,8.0,6891,47542,28789

In [283]:
print(final_data.shape)
print(final_data.head())

(4559, 16)
   county_fips    state county  year  total_investment_dollars  \
0         1007  Alabama   Bibb  2015                   1273871
1         1007  Alabama   Bibb  2016                    658855
2         1007  Alabama   Bibb  2017                   1710111
3         1007  Alabama   Bibb  2018                   2219547
4         1007  Alabama   Bibb  2019                   1596396

   total_number_of_investments  total_population  population_below_poverty  \
0                           10             20767                      3488
1                            7             20603                      3390
2                           15             20555                      3133
3                           16             20468                      2863
4                           13             20632                      3740

   population_below_poverty_percent  \
0                              16.8
1                              16.5
2                              15.2
3                              14.0
4                              18.1

   adults_25_and_older_less_than_high_school_graduate  \
0                                               2381
1                                               2408
2                                               2170
3                                               1994
4                                               2714

   adults_25_and_older_less_than_high_school_graduate_percent  \
0                                               11.5
1                                               11.7
2                                               10.6
3                                                9.7
4                                               13.2

   adults_25_and_older_with_bachelor's_degree_or_higher  \
0                                               1657
1                                               1878
2                                               2061
3                                               1784
4                                               1649

   adults_25_and_older_with_bachelor's_degree_or_higher_percent  \
0                                                8.0
1                                                9.1
2                                               10.0
3                                                8.7
4                                                8.0

   number_of_households  average_income_per_household  total_median_earnings
0                  7027                         38678                  29113
1                  7048                         39776                  30328
2                  6916                         43404                  31833
3                  6840                         45340                  32108
4                  6891                         47542                  28789

In [133]:
import geopandas as gpd

In [134]:
os.chdir(r"c:\Atharv\Git\fahe")
print(os.getcwd())

c:\Atharv\Git\fahe

In [135]:
# Read the shapefile using a raw string to avoid invalid escape sequence errors
gdf = gpd.read_file(r'cb_2018_us_county_5m\cb_2018_us_county_5m.shp')

In [136]:
from pathlib import Path

In [137]:
# Geometry: keep only FIPS + geometry, pad to 5 digits
gdf_slim = gdf[["GEOID", "geometry"]].copy()
gdf_slim["GEOID"] = gdf_slim["GEOID"].astype(str).str.zfill(5)

In [138]:
#Ensure county_fips exists and is 5-digit string
final_data = final_data.copy()

if "county_fips" not in final_data.columns:
    # derive from geo_id/GEO_ID if needed
    if "geo_id" in final_data.columns:
        final_data["county_fips"] = final_data["geo_id"].astype(str).str[-5:]
    elif "GEO_ID" in final_data.columns:
        final_data["county_fips"] = final_data["GEO_ID"].astype(str).str[-5:]
    else:
        raise KeyError("Need 'county_fips' or a 'geo_id'/'GEO_ID' to derive it.")

final_data["county_fips"] = final_data["county_fips"].astype(str).str.zfill(5)

In [139]:
#Join on county_fips ↔ GEOID
final_data = final_data.merge(
    gdf_slim.rename(columns={"GEOID": "county_fips"}),
    on="county_fips",
    how="left"
)

In [140]:
# Drop rows where year is 2024 or 2025
if "year" in final_data.columns:
    final_data = final_data[~final_data["year"].isin([2024, 2025])]

In [141]:
final_data.head(15)

,county_fips,state,county,year,total_investment_dollars,total_number_of_investments,total_population,population_below_poverty,population_below_poverty_percent,adults_25_and_older_less_than_high_school_graduate,adults_25_and_older_less_than_high_school_graduate_percent,adults_25_and_older_with_bachelor's_degree_or_higher,adults_25_and_older_with_bachelor's_degree_or_higher_percent,number_of_households,average_income_per_household,total_median_earnings,geometry
0,01007,Alabama,Bibb,2015,1273871,10,20767,3488,16.8,2381,11.5,1657,8.0,7027,38678,29113,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
1,01007,Alabama,Bibb,2016,658855,7,20603,3390,16.5,2408,11.7,1878,9.1,7048,39776,30328,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
2,01007,Alabama,Bibb,2017,1710111,15,20555,3133,15.2,2170,10.6,2061,10.0,6916,43404,31833,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
3,01007,Alabama,Bibb,2018,2219547,16,20468,2863,14.0,1994,9.7,1784,8.7,6840,45340,32108,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
4,01007,Alabama,Bibb,2019,1596396,13,20632,3740,18.1,2714,13.2,1649,8.0,6891,47542,28789,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
5,01007,Alabama,Bibb,2020,3081776,23,20748,3755,18.1,2474,11.9,1781,8.6,7259,51721,33912,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
6,01007,Alabama,Bibb,2021,1863006,10,21000,3558,16.9,2569,12.2,1877,8.9,7083,54277,32759,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
7,01007,Alabama,Bibb,2022,2861941,17,20836,4297,20.6,2783,13.4,1739,8.3,7216,50669,32546,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
8,01007,Alabama,Bibb,2023,1414540,9,20759,4258,20.5,2603,12.5,1795,8.6,7571,51215,34001,"POLYGON ((-87.42194 33.00338, -87.31854 33.006..."
11,01009,Alabama,Blount,2015,8956456,75,57126,9552,16.7,8277,14.5,5060,8.9,20816,45813,34549,"POLYGON ((-86.96336 33.85822, -86.9202 33.8734..."
12,01009,Alabama,Blount,2016,10003124,83,57099,9441,16.5,7705,13.5,5116,9.0,20619,46212,35743,"POLYGON ((-86.96336 33.85822, -86.9202 33.8734..."
13,01009,Alabama,Blount,2017,13829978,112,57051,8919,15.6,7791,13.7,5147,9.0,20690,47412,36757,"POLYGON ((-86.96336 33.85822, -86.9202 33.8734..."
14,01009,Alabama,Blount,2018,11802887,92,57082,8220,14.4,7685,13.5,4989,8.7,20600,48695,37178,"POLYGON ((-86.96336 33.85822, -86.9202 33.8734..."
15,01009,Alabama,Blount,2019,11196969,83,57108,7739,13.6,7568,13.3,5188,9.1,20847,49358,39004,"POLYGON ((-86.96336 33.85822, -86.9202 33.8734..."
16,01009,Alabama,Blount,2020,16249571,109,57127,7847,13.7,6642,11.6,5247,9.2,21205,48922,38662,"POLYGON ((-86.96336 33.85822, -86.9202 33.8734..."

In [142]:
os.chdir(r"c:\Atharv\Git\fahe\final")
print(os.getcwd())

c:\Atharv\Git\fahe\final

In [144]:
# Save as one big GeoJSON
gdf_out = gpd.GeoDataFrame(final_data, geometry="geometry", crs="EPSG:4326")
out_path = Path(r"final_output.geojson")
gdf_out.to_file(out_path, driver="GeoJSON")
print("Saved:", out_path)

Saved: final_output.geojson